olimorris/codecompanion.nvim

README.md

docs: added lualine example

---

README.md
doc/codecompanion.txt
lua/codecompanion/config.lua
lua/codecompanion/keymaps.lua
lua/codecompanion/strategies/chat.lua
lua/codecompanion/strategies/inline.lua
lua/codecompanion/utils/highlights.lua
lua/codecompanion/utils/keymaps.lua
lua/codecompanion/utils/util.lua

feat: add inline diff view

---

lua/legendary/extensions/codecompanion.lua

Fixes codecompanion actions in legendary

fix(legendary): update require statement for keymaps

---

lua/codecompanion/adapters/ollama.lua

Hello again!
Loving the new total token feature by the way!
This is a PR to add Validation to the Ollama Schema, unfortunately due to the nature of Ollama it has to be a little open-ended as you can theoretically set the defaults to whatever you want in alot of cases, but at least this will prevent users from doing something you absolutely *cannot* do.

Ollama Validation Functions

---

lua/codecompanion/strategies/inline.lua

fix(inline): fix issue with repeated delete keymap

---

README.md
doc/codecompanion.txt

Updated documentation of settings related to lualine.
I saw this commit https://github.com/olimorris/codecompanion.nvim/commit/0378d2a927f9c9ae09f26f24ad15c7b0e3a5d45f and adapted the writing style.

docs: update autocmd callback for lualine

---

lua/codecompanion/utils/adapters.lua

fix(adapters): extend adapters

---

.github/ISSUE_TEMPLATE/bug_report.yml

Using lazy.nvim for repro as suggested in the [official documentation](https://lazy.folke.io/developers#reprolua)

Update minimal.lua in bug report

---

README.md
lua/codecompanion/config.lua
lua/codecompanion/helpers/diff/default.lua
lua/codecompanion/helpers/diff/mini_diff.lua

https://github.com/user-attachments/assets/f286893f-1d24-4e87-9ab1-8b499fad11cf
@bassamsdata - This is the output from my initial attempt to add back `mini.diff`. Is this how you expect it to look?

feat: add back mini.diff

---

README.md
lua/codecompanion/adapters/openai_compatible.lua
lua/spec/codecompanion/adapters/openai_compatible_spec.lua

Added support to any OpenAI compatible model, self-hosted or otherwise
Typical example is LMStudio, this could also be applicable to anyone experiencing the same usecase
- #328

Ezechukwu69 openai compatible

---

lua/codecompanion/helpers/tools/editor.lua

Use CDATA sections in editor tool XML schemas

---

lua/codecompanion/adapters/anthropic.lua

Use the [latest tag](https://docs.anthropic.com/en/docs/about-claude/models) instead of a specific Version.

feat(anthropic): update to latest anthropic models

---

lua/codecompanion/adapters/anthropic.lua

Anthropic [released](https://docs.anthropic.com/en/docs/about-claude/models) the new model of Haiku, so updating it to model 3.5: 
`claude-3-5-haiku-20241022`
Thank you

feat(adapters): update the new haiku model

---

lua/codecompanion/adapters/openai_compatible.lua

This PR makes sure to handle nil `content` fields in deltas that some API providers return for some deltas. This fixes #445!
(I also renamed the OpenAICompatible adapter to `OpenAICompatible.Adapter` instead of `Gemini.Adapter` — I assume the previous name was a copy/paste error.)
#445 
Screenshot of the CodeCompanion chat buffer working and correctly showing the CodeCompanion header for assistant responses:

Fix OpenAI-compatible adapter for API providers that allow nil content fields in deltas

---

lua/codecompanion/providers/actions/mini_pick.lua

Fixed the `action_palette` mini integration. I initially thought it was working because I had `vim.ui.select = require("mini.pick").ui_select`, which made it functional for me. However, if someone sets `display.action_palette.provider` to `mini_pick`, it doesn’t work correctly. Hopefully, this PR resolves the issue.
[comment](https://github.com/olimorris/codecompanion.nvim/pull/382#issuecomment-2495949237) mentioning the issue.
Thank you
edit: add some clarification

fix(mini): fix the action_palette mini provider

---

lua/codecompanion/utils/context.lua

Fixing #488:  
I've tested the fix with Telescope, MiniPick, various keymaps, and multiple scenarios. It should now properly handle any visual selection.
PR: #382
Thank you

fix(utils): fix edge cases in visual selection

---

lua/codecompanion/adapters/copilot.lua
lua/codecompanion/adapters/openai.lua

The copilot adapter has a similar response type as openai to allow for using the openai token counter handler.

feat(copilot): add token count handler using openai adapter

---

.github/workflows/spelling.yaml
doc/configuration/chat-buffer.md
doc/extending/prompts.md
doc/extending/tools.md
lua/codecompanion/adapters/huggingface.lua
lua/codecompanion/config.lua
lua/codecompanion/strategies/chat/init.lua
lua/codecompanion/strategies/chat/tools/cmd_runner.lua
lua/codecompanion/strategies/chat/tools/files.lua
lua/codecompanion/strategies/chat/tools/rag.lua
lua/codecompanion/strategies/cmd.lua
lua/codecompanion/strategies/inline/init.lua
lua/codecompanion/types.lua
lua/codecompanion/utils/native_bit.lua
lua/codecompanion/utils/xml/XmlParser.lua
lua/codecompanion/utils/xml/xml2lua.lua
typos.toml

Add spelling / typos workflow. This uses https://github.com/crate-ci/typos to check spelling via GHA.

Add spelling / typos workflow.

---

doc/codecompanion.txt
doc/configuration/adapters.md
lua/codecompanion/adapters/deepseek.lua
tests/adapters/test_deepseek.lua

Implement an adapter for DeepSeek.
Supports both deepseek-chat and R1.
Tool support does not work - it isn't supported at all for R1, and is labelled as 'unstable' for deepseek-chat.

DeepSeek Adapter

---

lua/codecompanion/adapters/deepseek.lua

This makes the DeepSeek adapter more aligned with the OpenAI endpoint. The main difference remaining how messages are formed

refactor(adapter): DeepSeek is more aligned with OpenAI

---

lua/codecompanion/strategies/chat/init.lua

Ref: #552 
Addresses the issue of the settings Tree-sitter query being scoped to the whole buffer

perf(chat): improve settings tree-sitter query

---

lua/codecompanion/adapters/deepseek.lua
lua/codecompanion/strategies/chat/init.lua

Reasoning is now displayed under H3 headers called "Reasoning". The response is displayed under a H3 header called "Response":

feat(deepseek): show reasoning output

---

lua/codecompanion/adapters/openai_compatible.lua

The OpenAI Compatible adapter makes repeated requests to the models endpoint when `display.chat.show_settings` is enabled because of the `InsertLeave` autocmds in the chat buffer. This fix caches the models endpoint to prevent this however this means that if any new models become available during the session, the user will need to restart Neovim (low probability).
#731

fix(adapter): #731 openai_compat adapter calling API

---

doc/extending/prompts.md

docs: update prompt guide

---

lua/codecompanion/strategies/chat/init.lua
tests/helpers.lua
tests/strategies/chat/test_settings.lua

fix(chat): display settings in chat buffer

---

lua/codecompanion/init.lua
plugin/codecompanion.lua

#750 introduced some sensible changes to the plugin (see [here](https://github.com/neovim/neovim/pull/29073)). However it introduced an issue with logging, somewhat bizarrely.

fix: logging

---

lua/codecompanion/adapters/init.lua

fix: ollama adapter

---

doc/extending/workspace.md
lua/codecompanion/strategies/chat/slash_commands/fetch.lua
lua/codecompanion/strategies/chat/slash_commands/init.lua
lua/codecompanion/strategies/chat/slash_commands/workspace.lua

Previously only files and symbols were supported.

feat: workspaces now support URLs

---

lua/codecompanion/strategies/chat/ui.lua

fix: `show_header_separator`

---

lua/codecompanion/strategies/chat/init.lua

When cancelling chats that are streaming, the request is halted and the buffer is frozen. This ensures that the cancellation ends gracefully.

fix(chat): better cancelling of requests

---

doc/codecompanion.txt
doc/extending/adapters.md
lua/codecompanion/adapters/copilot.lua

feat(copilot): add support for gemini 2.0 flash (#855)

---

lua/codecompanion/strategies/chat/init.lua

This was causing the xAI adapter to break in a somewhat bizarre fashion

fix(chat): incorrectly applying settings

---

lua/codecompanion/adapters/openai.lua
lua/codecompanion/strategies/chat/init.lua
scripts/panvimdoc-cleanup.lua

fix(openai): handle different finish reasons

---

lua/codecompanion/adapters/openai.lua

fix(openai): model streaming

---

lua/codecompanion/strategies/chat/slash_commands/terminal.lua

Previously the `/terminal`  command would share the entire contents of the terminal with the LLM. Now, it will only show the incremental changes.

feat(slash_cmds): terminal command only shows latest changes

---

lua/codecompanion/strategies/chat/init.lua
tests/strategies/chat/test_chat.lua

fix(chat): #906 ignore system prompt now works

---

lua/codecompanion/strategies/chat/init.lua

The yaml_parser was stored at module level not on the chat object. This caused it to be tied to a buffer number which could be deleted by the user
#915

Fix yaml parsing in chat buffer

---

lua/codecompanion/strategies/chat/debug.lua

Fix setting  debug window height and width

---

lua/codecompanion/strategies/inline/init.lua

fix(inline): setting placement from prompt library

---

doc/codecompanion.txt
doc/extending/adapters.md
lua/codecompanion/adapters/copilot.lua

Add claude 3.7 and claude 3.7 tought to copilot adapter

Add claude 3.7 to copilot adapter

---

lua/codecompanion/adapters/anthropic.lua

The addition of Claude-3.7-sonnet, introduced changes to the max tokens that Anthropic support. We hadn't correctly implemented the logic that caps 3.5-sonnet at its previous limit.
#1028

fix(adapters): max_tokens error with anthropic

---

lua/codecompanion/adapters/openai_compatible.lua

fix(adapters): openai_compatible hardcoded models endpoint

---

lua/codecompanion/providers/slash_commands/default.lua

feat(slash_cmds): remove git dependency for defualt provider

---

CONTRIBUTING.md

The new CONTRIBUTING.md file was generated using claude 3.7 sonnet from the repo code imported in Anthropic project. The prompt was:
```
Rewrite the CONTRIBUTING.md including more information about the whole
project so that help new developer getting start contributing
(e.g. code structure, debugger, logging, linter,
```

docs: improved CONTRIBUTING.md

---

lua/codecompanion/schema.lua
lua/codecompanion/strategies/chat/ui.lua

fix(ui): render settings in chat buffer

---

lua/codecompanion/providers/completion/blink/init.lua

At the moment, triggering completions at `/buf|` won't show items because the `ctx.trigger.kind` is `Invoked` rather than `TriggerCharacter`. This changes the get completions logic to use either the `ctx.trigger.character` or the character before the bounds of the current keyword (keyword is `buf` in the previous example). A few other changes:
- Adds a `callback()` when the plugin decides not to show completion items, so that blink.cmp doesn't consider the source to be hanging
- Adds type checking when `lazydev.nvim` is installed
- Uses `item.data` for source specific data
N/A
N/A

feat: blink completions on invoke, without trigger char

---

lua/codecompanion/strategies/chat/helpers.lua
lua/codecompanion/strategies/chat/init.lua
lua/codecompanion/strategies/chat/references.lua

References can work with roles that have a space in them

---

lua/codecompanion/strategies/chat/keymaps.lua

fix(chat): can set system prompt dynamically when switching adapters

---

lua/codecompanion/strategies/chat/agents/executor/init.lua
lua/codecompanion/strategies/chat/agents/tools/editor.lua
lua/codecompanion/strategies/chat/agents/tools/files.lua

refactor(tools): type annotations to tooling outputs

---

lua/codecompanion/strategies/init.lua

Input for user_prompt=true is ignored

---

lua/codecompanion/providers/completion/blink/init.lua

In <=0.13, blink.cmp will always apply the item with its built-in implementation and then call the source's `execute` function. The default behavior in 0.14+ (to be released), is to pass a `default_implementation` function that the source may optionally call. This avoids two issues that the codecompanion source has ran into: brackets being added, <C-g> closing fzf-lua
The code is backwards compatible with <= 0.13
Fixes #968
Fixes https://github.com/Saghen/blink.cmp/issues/1303

fix: disable default execute implementation for blink.cmp

---

lua/codecompanion/adapters/anthropic.lua

fix(adapters): anthropic inline editing

---

lua/codecompanion/adapters/copilot.lua
lua/codecompanion/adapters/openai_compatible.lua

fix(adapters): ensure cache_expires is set

---

lua/codecompanion/providers/actions/telescope.lua

This improves the CodeCompanion Telescope  provider action palette implementation by:
1. Adding a preview buffer that either shows the entry description or prompt content (useful to display custom user prompts)
2. Reworking the entry display to show both the entry name and strategy properly ordered in columns and with adequate highlights.
Before:
After:

Improve Telescope action implementation

---

lua/codecompanion/config.lua

Improve diff opt default

---

doc/codecompanion.txt
doc/usage/chat-buffer/index.md

See commit
I was confused why nothing happened when I pinned or watch on #buffer on /buffer on even in the window with my actual buffer.

docs: documenting how gq/gw works better

---

doc/getting-started.md

Small typo fix on docs: getting-started.md

Small typo fix on docs: getting-started.md

---

lua/codecompanion/adapters/openai.lua

fix(adapters): model choice in azure openai

---

lua/codecompanion/strategies/chat/agents/tools/files.lua

The edit method can now work for searching and replacing or writing the entire contents.

fix(tools): files tool can now edit files

---

lua/codecompanion/strategies/chat/agents/tools/files.lua

Previously, the `read` and `read_lines` actions were not sharing the output with the LLM.

fix(tools): file tool now outputs content to the LLM

---

lua/codecompanion/strategies/chat/agents/init.lua

fix(tools): auto_submitting processes requests in order

---

lua/codecompanion/strategies/chat/references.lua

fix(refs): do not parse non-existent message

---

lua/codecompanion/adapters/openai.lua

feat(openai): update models

---

lua/codecompanion/adapters/gemini.lua

feat(gemini): add gemini-2.5-flash

---

doc/.vitepress/config.mjs
doc/extensions/mcphub.md

Allow markdown files in the extension folder to be dynamically displayed in the menu.

docs: dynamically load extensions in the sidebar

---

doc/usage/chat-buffer/agents.md

Openai-compatible adapter has tool-use support (https://github.com/olimorris/codecompanion.nvim/pull/1141#issuecomment-2834567645). Update the relevant docs to reflect this.

docs(tools): Fix typos and updated information on openai-compatible adapter.

---

lua/codecompanion/providers/actions/telescope.lua

Respect indentation in telescope action palette preview

---

doc/configuration/system-prompt.md

fix: fix typo

---

doc/codecompanion.txt
doc/configuration/action-palette.md
lua/codecompanion/providers/actions/fzf_lua.lua
lua/codecompanion/providers/init.lua

Add fzf_lua action provider

---

lua/codecompanion/adapters/anthropic.lua

Ref: [Link](https://www.anthropic.com/news/claude-4)

feat(adapters): add new Anthropic models

---

lua/codecompanion/adapters/tavily.lua
lua/codecompanion/strategies/chat/agents/tools/web_search.lua
tests/adapters/test_tavily.lua

Plan is to allow non-llm adapters to define functionality through `methods`. This brings the tavily adapter in line with jina.

refactor(adapters): update tavily

---

lua/codecompanion/adapters/gemini.lua

Add gemini-2.5-pro-preview-06-05

---

lua/codecompanion/strategies/inline/init.lua
tests/strategies/inline/test_inline.lua

fix(inline): chat placements with claude-sonnet-4

---

lua/codecompanion/strategies/chat/agents/tools/helpers/patch.lua
lua/codecompanion/strategies/chat/slash_commands/buffer.lua
lua/codecompanion/strategies/chat/variables/buffer.lua

Further refinements to make the tool more robust.
#1619

refactor(tools): improve system prompt in `insert_edit_into_file` tool

---

doc/extensions/vectorcode.md

The 0.7.0 VectorCode release will contain major (and breaking) refactoring to the codecompanion tools. This will make the VectorCode more flexible and more capable. This PR contains the updated extension page. I'll convert this to "ready for review" once I'm done on the VectorCode side.
https://github.com/Davidyz/VectorCode/discussions/191

Update VectorCode extension documentation for v0.7

---

lua/codecompanion/adapters/copilot.lua

As outlined in #1717, the Copilot adapter would consume an unnecessary amount of [Premium Requests](https://docs.github.com/en/copilot/concepts/copilot-billing/understanding-and-managing-requests-in-copilot#what-are-premium-requests) when using tools.
It transpired that this was because the Copilot adapter wasn't setting the `X-Initiator` header to be `agent`. This PR now does this and in the process fixes the request consumption issue.
#1717

Reduce Premium Requests with Copilot Adapter

---

doc/codecompanion.txt
lua/codecompanion/strategies/chat/agents/tools/helpers/patch.lua
tests/strategies/chat/agents/tools/helpers/test_patch.lua

**Issue:**  
Previously, patches would fail to apply if the file was empty or had fewer lines than the context required by the patch (e.g., patch expects 6 lines of context but file has only 1-2 lines). This caused all changes to be rejected due to low confidence in matching.
**Fix:**  
This ensures patches can be applied even when the file is too small or empty for the expected context.
- Added `is_simple_append` to `patch.lua` helper to detect when a patch is a simple append to an empty or small file.
- Updated `apply_change` to use this logic, allowing patches to be applied in these cases.
**Tests:**  
- Added tests for empty files and small files with excessive or missing context in the patch.
- Added a test for inserting multiple lines into a small module file.
From my personal …

 fix(tools): Handle patch application for empty and small files with insufficient context

---

README.md
doc/codecompanion.txt
doc/getting-started.md
doc/index.md

docs:update for new logo

---

lua/codecompanion/strategies/chat/tools/init.lua
lua/codecompanion/strategies/chat/tools/orchestrator.lua

Adding additional resiliency to the tools implementation

fix(tools): additional resiliency

---

lua/codecompanion/strategies/chat/ui/folds.lua
lua/codecompanion/strategies/chat/ui/formatters/reasoning.lua
lua/codecompanion/strategies/chat/ui/formatters/standard.lua
lua/codecompanion/strategies/chat/ui/formatters/tools.lua

refactor(ui): better uniformity across formatters

---

lua/codecompanion/config.lua

Update the conditional in the default system prompt.
#2042

fix(chat): system prompt resolving

---

lua/codecompanion/strategies/chat/memory/helpers.lua
tests/strategies/chat/memory/test_memory.lua

When loading multiple memories into a chat buffer, prevent the same file from being added as context

fix(chat): don't add duplicate memory

---

.codecompanion/tests/test.md
.codecompanion/workflows.md
lua/codecompanion/config.lua

chore: add new workflow memory and update test workflow

---

lua/codecompanion/init.lua
tests/test_cmds.lua

fix(chat): infinite loop when toggling chat
