lua/codecompanion/actions.lua
Hi Oli,
I'm a big fan of `onedarkpro.nvim` and I'm excited about this project and the level of polish to it.
This PR is a small tweak to extend the `Chat as` actions. I hope it might provide some value. I understand your involvement in further development may be minimal, but if your circumstances permit, I'm looking forward to making more meaningful contributions as I integrate this plugin into my work and personal workflow.
Thanks,
Yomi
=> Add Rust action to `actions.lua`

plugin/codecompanion.lua
=> fix: Get prompt from vim.ui.input() if no args provided to :CodeCompanion

README.md, lua/codecompanion/config.lua
Allows using lazy.nvim `opts` (declarative) instead of having to use a `config` function (imperative)
=> feat(config): Allow specifying adapters by string

README.md, doc/codecompanion.txt, lua/codecompanion/adapter.lua, lua/codecompanion/utils/util.lua
Having the API key in environment variables is not always safe, as any application or program can read it.
> I also had a situation where a program didn't load the project specific `.env` file but used the main key from the user profile - although, this case can be rectified with the recent pattern using a different variable name.
This PR allows for this:
```lua
chat = require("codecompanion.adapters").use("openai", {
env = {
api_key = "cmd:gpg --decrypt ~/.openai-api-key.gpg 2>/dev/null",
},
}),
```
I'm happy to make further changes; this change breaks assumptions about what the config should be.
=> Add support for a shell command in place of environment variable name

lua/codecompanion/utils/ui.lua
If the user does not have telescope installed, then `CodeCompanionActions` errors out. This PR checks if telescope is installed, and adds it to the `vim.ui.select` opts only if it exists. Otherwise, use the default opts.
=> CodeCompanionActions - Only use telescope if exists

README.md, doc/codecompanion.txt, lua/codecompanion/actions.lua, lua/codecompanion/agent.lua, lua/codecompanion/init.lua, lua/codecompanion/strategies/chat.lua
As per Andrew Ng's beautifully explained [tweet](https://twitter.com/AndrewYNg/status/1773393357022298617).
Initial plan is to support reflection in an automated fashion...that is, prompt the LLM to self reflect on its own work (without the user having to interact with the chat buffer).
In the future we'll figure out a way to add support for tooling and I will endeavour to make sure all of this can be done in the chat buffer.
=> feat: add agentic workflows to the plugin

lua/codecompanion/actions.lua
Change list:
- Improve the system prompt for the agent workflows 
- use chain-of-thought, and step-back prompting.
- Condenses the final two user prompts into one prompt that just outputs the expected code
=> Improve system and final user prompt for agent workflow

lua/codecompanion/adapters/openai.lua
Some third-party OpenAI forwarding services may have a return data with an empty json.choices.
=> fix: Handled cases with empty json.choices in OpenAI adapter. 

lua/codecompanion/adapters/ollama.lua
This is a fix for https://github.com/olimorris/codecompanion.nvim/issues/67.
If a user has a `:latest` model installed on their system it should also add the model without a tag. Generally I just use `llama3` in my config file and this was throwing a validation as I *technically* have `llama3:latest` on my system.
=> Fix: Include base model name for entries in ollama

lua/codecompanion/adapters/ollama.lua
As @davidgumberg mentioned here: https://github.com/olimorris/codecompanion.nvim/pull/61#issuecomment-2237751169
`num_predict` is incorrectly documented on Ollama's docs, we should adjust the default value of `num_predict` to reflect this.
Also, I agree with @davidgumberg's point that we should probably nil out the values that ollama states as we should grab this from the modelfile, but ideally we should try find a way to do this so that the values are being shown to the user. I am investigating this at the moment. This fix is just a temporary measure to fix what is an incorrect value.
=> Fixed the Num_Predict default value

doc/RECIPES.md, lua/codecompanion/actions.lua
https://github.com/olimorris/codecompanion.nvim/commit/e4466f8242821da4b784df88a604bad13b8e9b52 moved the `get_code` function to `codecompanion.helpers.actions`, but the send_code action still tries to call it from helpers.code, resulting in a crash.
=> Fix last instance of `get_code` being called from `codecompanion.helpers.code`

README.md, lua/codecompanion/actions.lua, lua/codecompanion/config.lua, lua/codecompanion/init.lua, lua/codecompanion/keymaps.lua, lua/codecompanion/prompts.lua, lua/codecompanion/strategies.lua, lua/codecompanion/strategies/chat.lua, lua/codecompanion/strategies/saved_chats.lua, lua/codecompanion/utils/context.lua, lua/codecompanion/utils/util.lua, lua/codecompanion/workflow.lua
Users can now move between open chat buffers with `}` and `{`. There is prevention built into the plugin to stop multiple chat buffers being open at the same time. Global variables have also been reduced.
=> feat: better workflow

lua/codecompanion/utils/keymaps.lua
After updating the plugin, which-key stopped displaying descriptions for buffer keymaps.
This one fixes it and allows to overwrite default action description.
=> fix: add missing description when setting keymaps

lua/codecompanion/strategies/inline.lua
support stop_context_insertion  logic in inline strategy
Sometimes we need modify the visual selected code sended to model.
=> feat(inline): support stop_context_insertion  logic in inline strategy

lua/codecompanion/prompts.lua
For prompts with `opts.default_prompt` set to `true` don't we should not create keybindings if `use_default_prompt` is set to `false`.
=> fix: avoid setting keybindings if use_default_prompt=false

lua/codecompanion/init.lua
I have encountered this error when not having `strategies` set in the configuration.
```
attempt to index field 'strategies' (a nil value)
```
This commit adds a check to prevent this error.
=> fix: Prevent nil error

README.md, lua/codecompanion/config.lua
Updated the keybindings for navigating to the next and previous headers from `]` to `]]` and from `[` to `[[` respectively in both the README and configuration files.
It's pretty common to use `[` and `]` as first char in Vim/Neovim motion keymaps. So the editor usually pause for a couple of milliseconds before process `[` and `]` as standalone motion.
=> fix(keymaps): update next and previous header keybindings

README.md, lua/codecompanion/helpers/slash_commands/file.lua
related to #166
This PR introduces support for the mini.pick plugin as an alternative file selector for the `/file` command. It allows users to use mini.pick for file selection when Telescope isn’t available, offering greater flexibility and compatibility with various Neovim setups.
I haven’t used Telescope in a long time, and since the slash /file command requires the Telescope plugin, it’s a feature I haven’t really been able to use.
screenshot for mini.pick
=> Adding mini.pick as an alternative to telescope for /file command

README.md, lua/codecompanion/helpers/slash_commands/file.lua
After the last refactor of file.lua, `mini.pick` stopped working. with error:
```lua
...n.nvim/lua/codecompanion/helpers/slash_commands/file.lua:21: attempt to index global 'file' (a nil value)
```
so it's just a small modification to allow it to work.
#169
Thank you
=> Accommodate mini.pick to with with relative path

lua/codecompanion/helpers/slash_commands/buffer.lua, lua/codecompanion/helpers/slash_commands/file.lua
I noticed that mini.pick wasn’t closing properly but didn’t have the time to fix it, so thank you for addressing that. This PR simply ensures the window closes correctly as outlined in the `mini.pick` documentation.
After the latest update, I noticed some flickering in mini.pick. I believe this PR should fully resolve the issue by always passing `nil` after selecting a file or buffer.
thank you
=> fix: properly closing Mini.pick after choosing file/buffer

lua/cmp_codecompanion/slash_commands.lua
Callback execution in source.execute() for slash commands so that cmp ends correctly.
#197
=> ensure callback execution in source:execute

doc/codecompanion-tools.txt
This PR fixes the naming in the documentation which leads to duplicate tags (if you build it with nix). Hopefully I renamed and formatted everything correct again 😄 
Its only a small fix for the documentation which occurs for example if you try to build the plugin with nix:
```
> E154: Duplicate tag "codecompanion-table-of-contents" in file /nix/store/yqpyyaqmabfv3r4ik3yxfr3mkvkaqx9g-vimplugin-codecompanion.nvim-2024-09-16/./doc/codecompanion.txt
> E154: Duplicate tag "codecompanion.txt" in file /nix/store/yqpyyaqmabfv3r4ik3yxfr3mkvkaqx9g-vimplugin-codecompanion.nvim-2024-09-16/./doc/codecompanion.txtFailed to build help tags!
For full logs, run 'nix log /nix/store/i52zgxq9irxx7hwriwzc0vp5i2yz16ha-vimplugin-codecompanion.nvim-2024-09-16.drv'.
```
=> Fix duplicate tags in help

lua/codecompanion/helpers/tools/editor.lua
The `config.display.inline.diff.provider` option is nil, so I guess it should be `config.opts.diff.provider`
=> Fix diff provider in editor tool

README.md, lua/codecompanion/commands.lua, lua/codecompanion/config.lua, lua/codecompanion/init.lua, lua/codecompanion/strategies.lua, lua/codecompanion/strategies/inline.lua
I don‘t use dressing for inputs so I have the problem that the input is missing a space at the end of the "Prompt" input. A solution would be to just add the space everywhere, but I think it's also fun to have the ability to customize the prompt field. I also deleted the warning for the input, mainly to stay consistent for all inputs.
The current implementation doesn‘t look good if you don‘t have dressing enabled for input fields:
=> Allow to customize prompt

README.md
Double quotes don't seem to work in this context.
=> README: fix vim-plug instructions

lua/codecompanion/init.lua
With cd6ac62a82e98527850ad419ef59165197629f10, a null access happens when running `:CodeCompanionChat`:
This PR fixes that by making sure that `fargs` isn't empty before indexing into it.
=> fix(chat): don't index an empty table

lua/codecompanion/config.lua, lua/codecompanion/helpers/slash_commands/help.lua
This pull request introduces the `mini.pick` plugin as a provider for the `/help` command.
This implementation mirrors the functionality established in the `/file` and `/buffer` commands by utilizing a similar structure and logic.
No issues.
Thank you
=> feat: add mini_pick to /help command

lua/codecompanion/actions/prompt_library.lua
This commit introduces the `picker` field to the prompt resolution process in the `prompt_library.lua` file.
Resolve issue when using custom prompt with picker
- Fixes #274 
Error executing vim.schedule lua callback: ...decompanion.nvim/lua/codecompanion/strategies/inline.lua:404: bad argument #1 to 'ipairs' (table expe
cted, got nil)
[C]: in function 'ipairs'
...decompanion.nvim/lua/codecompanion/strategies/inline.lua:404: in function 'form_prompt'
...decompanion.nvim/lua/codecompanion/strategies/inline.lua:226: in function 'cb'
...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:206: in function <...ocal/share/nvim/lazy/dressing.nvim/lua/dressing/util.lua:2
02>
=> feat(prompt_library): add picker field to prompt resolution #274

README.md, lua/codecompanion/actions/providers/mini_pick.lua
This pull request introduces the `mini.pick` plugin as a provider for the `CodeCompanionActions` command, aligning with the Telescope integration in v4 (#260).
**Note:** The only issue with this implementation is that after selecting an item, the cursor remains in the current buffer instead of jumping to the chat buffer. I attempted several fixes without success, so it might need revisiting. However, it's not a major concern and could be addressed later by me or someone else.
Thank you!
No issues
=> feat: add mini pick to actions

lua/codecompanion/actions/prompt_library.lua
This PR fixes the issue with `condition` fields in the `prompt_library` option. The `resolve` function does not carry over the setting, and it is therefor not used.
I also sorted the fields, just for improve readability and maintainability.
- Reordered fields in the table inserted into `_prompts`:
- Added `condition` field.
- Moved `name` field after `description`.
- Moved `strategy` field to the end.
- Fixes https://github.com/olimorris/codecompanion.nvim/issues/268
=> fix: prompt library conditionals

doc/ADAPTERS.md, doc/codecompanion-adapters.txt, lua/codecompanion/adapters.lua, lua/codecompanion/adapters/anthropic.lua, lua/codecompanion/adapters/copilot.lua, lua/codecompanion/adapters/gemini.lua, lua/codecompanion/adapters/ollama.lua, lua/codecompanion/adapters/openai.lua, lua/codecompanion/strategies/chat.lua, lua/codecompanion/strategies/inline.lua, lua/spec/codecompanion/adapters/helpers.lua
Update openai adapter data parsing (also used by copilot) when stream is set to false.
When stream is set to false the format do not start with `data: ` and message content is in `json.choices[1].message.content` (see #261 log output for the format)
- Fixes #261
=> fix!(copilot): data parsing when stream is false

lua/codecompanion/init.lua
The call to `context_utils.get(..)` marks `args` as optional.
=> Fix type for prompt()

lua/codecompanion/config.lua
Always using the default diff is more stable, users who want to use another diff program can create a new slash command.
=> Use default diff in `/commit` command

lua/codecompanion/strategies/inline.lua
The edits were inserted in a streaming way, polluting the insert history. 
@olimorris this has the assumption that `overwrite_selection(self.context)` is called before inserting, so the first insert is combined with the deletion.
If this is not the case, it is merged with the last edit the user made, which would be bad.
[nvim/discussions/325#discussioncomment-10990915)](https://github.com/olimorris/codecompanion.nvim/discussions/325#discussioncomment-10990915)
=> Add undojoin for inline inserts

lua/codecompanion/adapters/anthropic.lua
Anthropic released an updated sonnet 3.5 model version `claude-3-5-sonnet-20241022`
=> chore: update latest sonnet-3-5 version (claude-3-5-sonnet-20241022)

lua/codecompanion/helpers/diff/default.lua
This patch fixes the issue that the diff split is opened in chat window instead of the source window when the diff layout is "horizontal" and the chat window layout is "vertical".
N/A
Before (diff split window opened in chat window):
After (diff split window opened below source window):
=> fix(diff): diff split window wrongly opened in chat window

lua/codecompanion/config.lua, lua/codecompanion/keymaps.lua, lua/codecompanion/strategies/chat.lua
Thank you for the amazing plugin, I love it! Works amazing with the claude for me. 
I wanted to make a small improvement to the `yank code` functionality:
When cursor is inside the code block `yank code` keymap would copy focused codeblock instead of the last one. 
When user wants to copy the last one they would easily jump out of the current code block and press `gy` to copy the last codeblock.
We can also make this addition opt in or opt out in the config. 
Personally I also use `vim.highlight.on_yank`, and it is a bit sad that this is not working with the `yank code` function. 
What do you think about actually jumping to the codeblock, and yanking it with the build in vim yank instead of `vim.fn.setreg` ?
Decided not to open a discussion since this this a very small change and I'll …
=> feat(keymaps): `yank_code` copy focused or the last codeblock.

README.md, doc/codecompanion.txt, lua/codecompanion/adapters/azure_openai.lua, lua/codecompanion/config.lua
As discussed in https://github.com/olimorris/codecompanion.nvim/discussions/383 I added a new adapter using the OpenAI adapter handlers comparable to xAI and Copilot.
The adapter uses these env vars:
```lua
env = {
api_key = "AZURE_OPENAI_API_KEY",
endpoint = "AZURE_OPENAI_ENDPOINT",
api_version = "2024-06-01",
deployment = "schema.model",
}
```
The first two are also used in the [official OpenAI Python library](https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart?tabs=command-line%2Cjavascript-keyless%2Ctypescript-keyless%2Cpython-new&pivots=programming-language-python#create-a-new-python-application), so they should be pretty standard. The api_version shouldn't change too often, maybe only for newly released models.
I'm not sure about the deployment. Azure OpenAI does …
=> feat(adapters): ✨ add Azure OpenAI

README.md, doc/codecompanion.txt, lua/codecompanion/config.lua, lua/codecompanion/strategies/chat.lua
add language configuration for LLM responses
- Add new 'language' option with default value "English"
- Convert static system prompt to function for language templating
- Add language requirement in system prompt
https://github.com/olimorris/codecompanion.nvim/discussions/409
=> feat: add language configuration for LLM responses

doc/codecompanion.txt, lua/codecompanion/strategies/chat/tools/cmd_runner.lua, lua/codecompanion/strategies/chat/tools/editor.lua, lua/codecompanion/strategies/chat/tools/files.lua, lua/codecompanion/strategies/chat/tools/rag.lua
As discussed in https://github.com/olimorris/codecompanion.nvim/discussions/416, in some cases, the agents were not able to execute actions because the `tools` XML was not being parsed correctly. It was due to the fact that the ```xml syntax was not being used for the `tools` XML code block.
- Implements https://github.com/olimorris/codecompanion.nvim/discussions/416
=> fix(tools): add XML block formatting guidance

lua/codecompanion/strategies/chat/slash_commands/shared/files.lua
Accomedate Mini_pick to allow selection of files in the /file command.
commit 6184bd4e60d4f301cc5f47416a9a90731eb7f8fb
Thank you
=> feat(mini_pick): allow multi selection in /files

lua/codecompanion/strategies/inline.lua
In this particular circumstance with a visual selection when running `:CodeCompanion <write a promp>` it will use this logic branch in the code to put together the markdown codeblock, but instead of concatenating the lines with a `\n` line break, it uses `  ` two spaces. All other codecompanion features operate using `\n`. This PR makes it consistent with the rest of the plugin.
- Fixes #426
See linked gh issue for screenshots.
=> fix(inline): #426 concat lines with `"\n"` instead of `"  "` two spaces

lua/codecompanion/actions/static.lua
The `open` method is now in the ui module as of: c902222
Fixes this error when opening a chat from the "Open Chats" action (`:CodeCompanionActions` => "Open chats" => select):
```
Error executing vim.schedule lua callback: .../codecompanion.nvim/lua/codecompanion/actions/static.lua:69: attempt to call method 'open' (a nil value)
.../codecompanion.nvim/lua/codecompanion/actions/static.lua:69: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```
=> Use correct method in open chats call

README.md, doc/codecompanion.txt
Update the docs for the `render_headers` config option change to `show_header_separator`.
=> docs: update render_headers to show_header_separator

lua/codecompanion/adapters/gemini.lua, tests/adapters/test_gemini.lua
gemini doesn't respect `gs` to remove system prompt and therefore it produces an error.
fix: #528
=> fix(adapters): fix gemini respect system prompt removed

lua/codecompanion/utils/treesitter.lua
Use vim.treesitter instead of calls to nvim-treesitter.
Pull in two functions from nvim-treesitter.ts_utils that no longer exist on `main`
- Fixes #542
=> Use vim.treesitter instead of calls to nvim-treesitter.

README.md, doc/codecompanion.txt
Lazy.nvim will by default not load a plugin until ultimately needed. One way to load the plugin is to enter the CodeCompanion* commands.
Add the commands using `cmd` that will make the plugin load.
=> docs: add cmd for Lazy.nvim

README.md
When adding `blink.cmp` completion with codecompanion to [my config](https://github.com/fredrikaverpil/dotfiles/blob/baf5af27f6c50a49bc87d411d2e557ee8783eb9b/nvim-fredrik/lua/fredrik/plugins/codecompanion.lua#L105-L121), I noticed the docs showed an outdated setup example.
I replaced the lua code snippet with a complete example.
=> docs: fix blink.cmp example

lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/types.lua
This PR looks to optimize Tree-sitter parser usage in the chat buffer
#552 has reported that a large chat buffer _may_ cause Neovim to balloon in memory usage
=> refactor: optimize ts parser usage

minimal.lua
`minimal.lua` make use of the old `sources.completion.enabled_providers` setting. Newer version of blink now use `sources.default`. This is the same as provided in the codecompanion.nvim README example.
=> chore: update blink config in minimal.lua

lua/codecompanion/adapters/openai_compatible.lua, lua/codecompanion/strategies/chat/references.lua
Object nesting between the chat buffer and the references object are now reduced.
#552
=> fix: references performance

doc/RECIPES.md
Thanks for the amazing plugin!
This PR just corrects a small typo on the recipes file.
=> Small typo fix on `RECIPES.md`

lua/codecompanion/init.lua
I often found that the first time I would use CodeCompanion would be to add some code to the chat and ask a question. I kept running into the issue where I had not initialized the chat window yet so I would get a "No chat buffer found" warning.
I figured it would be nice if it automatically created a new chat, if one does not already exist when the user calls `:CodeCompanionChat Add`
- [✓ ] I've read the [CONTRIBUTING](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines and have adhered to them in this PR
- [✓] I've updated the README and ran the `make docs` command
=> feat(chat): adding to chat initializes buffer if needed

lua/codecompanion/adapters/gemini.lua, lua/codecompanion/strategies/inline.lua
I've been having issues with `gemini-2.0-flash-exp` returning code blocks inline, despite the prompt not to. As well as bad classifications... This is an issue with `gemini-2.0-flash-exp`, not CodeCompanion. However I saw other people were having the same issue so thought I'd put out what's worked for me.
This will manually strip out the code blocking if the model is set to `gemini-2.0-flash-exp`. I have also added one more example to the `PLACEMENT_PROMPT` that seems to help with classification a lot.
https://github.com/olimorris/codecompanion.nvim/issues/536
- [✓ ] I've read the [CONTRIBUTING](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md) guidelines and have adhered to them in this PR
- [✓] I've updated the README and ran the `make docs` command
=> fix(inline): fixes gemini-2.0-flash-exp code blocking

README.md
I completely forgot we should probably add this, just in case. Not sure it's worth explaining why `opts_extend` is there?
https://github.com/olimorris/codecompanion.nvim/discussions/578#discussion-7758770
=> docs: add opts_extend

lua/codecompanion/strategies/chat/keymaps.lua
@olimorris Note: this PR is on top of my other PR #581 so includes those changes (minimal). So if you reject that one or change it, just need to update in this PR accordingly.
Currently if you try to do two completions in the same line, it deletes everything after the first completion and just provides completions items for that first keyword. See the following as example:
(cursor at end of line below, after `#ls`)
```
I am writing a message and want to reference `#buffer` and include `#ls`
```
When I try to do a completion after `#ls` (for `#lsp`), it jumps back to the first found completion keyword in the line (`#buffer`) and removes everything after it... the following is removed: ` and include #ls` 
It is because the current code is just checking across the entire line for the first …
=> Fix completions keymap to allow for multiple completion keywords in a single line

lua/codecompanion/init.lua
By default, blink's `path` provider has a score offset of 3, meaning that completions for slash commands in the buffer are deep down below possible path completions in the list of suggestions.
Since this suggestion only triggers in the chat buffer, it is reasonable to assume that slashcommands are much more likely to be the correct suggestions than folders at `/`.
Before:
After:
=> feat(completion): Boost score of blink completion suggestions

.github/ISSUE_TEMPLATE/bug_report.yml, minimal.lua
Updates the minimal config for bug repro to reflect the new recommended basic config relying on automatic blink registration.
=> chore: Update minimal config for bug repro

lua/codecompanion/commands.lua
`:CodeCompanion<Cr>` now behaves the same as  `:CodeCompanion /buffer<Cr>` if you add `/buffer` as the text in the input field.
Fixes #614
=> handle library promts in `:CodeCompanion<Cr>`

lua/codecompanion/strategies/inline/init.lua
When using the "before" placement, if the placement happens on the first column (0), it shouldn't try to move the cursor to the previous column, resulting in a negative column index.
Fixes #613
Note: I only fixed this for `pos.col`, not `pos.line`; I haven't observed any issues with negative line indexing, so I wanted to avoid changing anything for lines, in case it breaks other expectations or clamping of lines already happens in other places (e.g. `vim.api.nvim_buf_set_lines` has the following documentation note: "Out-of-bounds indices are clamped to the nearest valid value, unless `strict_indexing` is set.").
=> avoid negative column indexing

lua/codecompanion/providers/completion/blink/init.lua
Slash command completion was failing preventing the blink.cmp completion from properly showing (particularly with fzf-lua).
Mentioned in discussion [here](https://github.com/olimorris/codecompanion.nvim/discussions/578)
=> fix(blink.cmp) completion was failing for slash commands

lua/codecompanion/utils/yaml.lua
Current yaml decoding does not decode "boolean_scalar" fields, e.g.
```yaml
is_two_even: true
is_three_even: false
```
=> fix(utils): parse "boolean_scalar" fields when decoding yaml

lua/codecompanion/init.lua
It happened to me that I had blink cmp declared as a dependency and never used (and I know it is a bad practice), and I couldn't understand why the slash commands weren't working in the chat. This should give an heads up to people who could face the same problem
=> Raising error when both blink and cmp are available

doc/installation.md, lua/codecompanion/init.lua
I've added support for plugins to add `per_filetype` sources dynamically. It will fail if the user has set the `per_filetype` to a function, which should be extremely rare for this case. Open to feedback on the API! It's currently only available on `main`, and will be included in the next release (0.11.0).
I've also switched the recommended setup for <= 0.10.0 to use `sources.per_filetype` to avoid conflicts with other sources.
P.S. apologies for all the blink.cmp issues you've had to deal with. If I had it my way, less people would be using my plugin while it's still in beta :smile: Love the new docs site!
N/A
N/A
=> feat: register source for filetype in blink.cmp

lua/codecompanion/adapters/deepseek.lua, tests/adapters/test_deepseek.lua
Deepseek R1 doesn't work when you don't have a `user` message after a `system` message. The current code transforms all messages (except first) with `system` roles to `assistant` roles. This logic breaks the chat when you have two or more system prompts at the beginning because Deepseek R1 requires a `user` message after a `system` message.
For example, if you try to send the following messages:
```
[
{ role: "system",  message: CodeCompanionMessage },
{ role: "system",  message: CustomMessage},
{ role: "user", message: question },
]
```
After transforming messages, you end up with:
```
[
{ role: "system",  message: CodeCompanionMessage },
{ role: "assistant",  message: CustomMessage},
{ role: "user", message: question },
]
```
This is not accepted by Deepseek, resulting in:
> Error: …
=> fix(deepseek): messages order in deepseek adapter

lua/codecompanion/strategies/chat/keymaps.lua
I was confused why I couldn't change my adapter to another one. I added notification to warn future users that show_settings disables the ability to change adapter.
=> chore: add notification

doc/codecompanion.txt, doc/getting-started.md
Merge mappings by using a table of modes instead of duplicating them.
=> docs: Simplify recommended mappings

lua/codecompanion/strategies/chat/slash_commands/symbols.lua
As mentioned in the issue I opened, I don't necessarily expect this PR to get accepted "as is" but wanted to show you the problem and my quick hacky solution to work for me given I work mostly with TypeScript and want this feature to work.
See details in this issue:
- #722
- #722 
- https://github.com/neovim/neovim/issues/27265
=> fix(symbols): typescript ft not recognized; map extension to ft

lua/codecompanion/strategies/chat/keymaps.lua
Adding support for reasoning broke the models picker. This is a fix for that
=> fix(picker): models picker doesn't show for deepseek adapter

lua/codecompanion/http.lua, lua/codecompanion/strategies/chat/init.lua
Pressing `q` in the chat buffer whilst chatting to an LLM is currently a cluster f*ck. This PR addresses that.
=> fix(chat): more graceful cancellations

lua/codecompanion/strategies/chat/slash_commands/fetch.lua
Trying to use the fetch slash command I was getting the error in the screenshot below.
=> fix(fetch): cached url folder needed to be created first on windows

lua/codecompanion/strategies/chat/slash_commands/workspace.lua
This is a weird one. I could not pinpoint the culprit, but if I started a chat convo, used /workspace slash command (works fine the first time), but then create a new convo and try /workspace slash again it gives a plenary error (see screenshot below).
The path arg going into the function is blank and somehow the CONSTANT for the path in that file is also suddenly blank.
You can see what I mean by the change in my commit (a couple lines). This solves my immediate problem but I have no clue if there is something more / deeper that has to be addressed 🤷‍♂️ 
No idea but curious if this is somehow related to #756 ?
=> fix(workspaces): workspace path constant cleared after first use

lua/codecompanion/adapters/ollama.lua
An odd bug occurred with Ollama whereby the model, if a function, wasn't getting expanded.
#769
=> Fix Ollama Adapter

lua/codecompanion/adapters/copilot.lua
Hi, thank you for the plugin.
I encountered a bug with the copilot provider: when opening the chat buffer and entering text, then pressing `Enter`, it crashes by outputting:
When looking at the source code, I found that you'll read only one line of the file:
```lua
local userdata = vim.json.decode(vim.fn.readfile(file_path)[1])
```
`vim.fn.readfile` returns a list of lines.
So this PR will adapt the code to read the content and then concatenate all lines of this content to pass to `json.decode`.
Maybe `vim.json.decode(vim.fn.readfile(file_path)[1])` was intended to fix an edge case.
Do not hesitate to tell me if something needs to be changed or to explain why it was done that way.
Thanks!
=> fix: handle multiline userdata in copilot adapter

queries/scala/symbols.scm
Add scala symbols following the pattern of using the defined symbols file in the Aerial library.
n/a
Screenshot with providing scala symbols referencing the plugin locally with this change.
=> feat: add symbols for scala

lua/codecompanion/strategies/chat/debug.lua
The new functionality to edit chat history doesn't work with adapters that have model defaults and choices that are functions (e.g. Ollama). This PR fixes that.
=> Fix debug window for adapters which have models as functions

lua/codecompanion/adapters/init.lua, lua/codecompanion/adapters/ollama.lua, lua/codecompanion/strategies/chat/init.lua
This refactor cleans up the fix that was implemented for Ollama not working after the chat debugging was added.
#769
=> refactor(adapters): schema->parameters is cleaned up

lua/codecompanion/utils/treesitter.lua
As we output adapter's reasoning under H3 headers, the current header navigation moves between ALL headers rather than just H2 ones. This fix addresses that.
=> fix(chat): navigate between roles in buffer

lua/codecompanion/strategies/chat/slash_commands/buffer.lua, lua/codecompanion/strategies/chat/slash_commands/fetch.lua, lua/codecompanion/strategies/chat/slash_commands/file.lua, lua/codecompanion/strategies/chat/slash_commands/help.lua, lua/codecompanion/strategies/chat/slash_commands/symbols.lua, lua/codecompanion/strategies/chat/slash_commands/terminal.lua, lua/codecompanion/strategies/chat/slash_commands/workspace.lua
Scopes were global which caused issues when mixing different slash commands with workspaces.
=> fix(slash_commands): scope constants to be local

doc/configuration/chat-buffer.md
The documentation currently nests the diff settings under `opts.display.chat.diff`, when they should really be under `opts.display.diff`.
=> fix diff provider documentation

lua/codecompanion/adapters/init.lua, lua/codecompanion/config.lua, lua/codecompanion/strategies/chat/debug.lua, lua/codecompanion/strategies/chat/init.lua, tests/adapters/test_ollama.lua, tests/helpers.lua, tests/strategies/chat/test_references.lua
Previously debugging the chat buffer for adapters such as Ollama was troublesome
=> fix(chat): can debug adapters with `schema.model.default` as a function

doc/configuration/chat-buffer.md
The previosly suggested markview config for chat buffer rendering is deprecated in markview. See the discussion #802
=> docs: update suggested markview configuration

lua/codecompanion/providers/slash_commands/mini_pick.lua
This addresses a bug that prevents slash commands from using mini_pick as a provider.
Fixes #803
=> Fix unavailable constant for mini_pick provider

doc/extending/workspace.md, lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/strategies/chat/slash_commands/workspace.lua, tests/strategies/chat/slash_commands/test_workspace.lua, tests/stubs/messages.lua, tests/stubs/workspace_multiple.json
When adding multiple workspaces to the chat buffer, system prompts were being duplicated. Also, top-level system prompts in the workspace file should come first ahead of group-level ones.
=> feat(workspaces): handle multiple workflows better

Makefile, doc/codecompanion.txt, scripts/panvimdoc-cleanup.lua, scripts/vimdoc.md
Adds scripts necessary to use panvimdoc to generate all docs.
The added `scripts/panvimdoc-cleanup.lua` is a pandoc filter that makes a few changes when generating the docs:
- A few headers are changed (see the table) to fit better in the text width
- Emphasis (italics in the docs website) are converted to backtick wrapped code elements, for a similar effect
- Some extra handling to fix `_@this_`, because it’s recognized as a citation
- I try to fix all of the links, but a few aren’t there yet. 
As is, there are a few links that aren’t properly found as tags. When you have relative links in the docs, it’s not easy to track where they came from. So for example, [L438](https://github.com/olimorris/codecompanion.nvim/blob/146ce88607acc4d6f7f7c96a0352b0c90ad6a2fd/doc/codecompanion.txt#L438) …
=> docs: add all docs to panvimdoc generation

lua/codecompanion/adapters/copilot.lua
o3-mini was released today so I decided to add it to your plugin while I was at it.
No related issue, just OpenAI panicking at Deepseek's R1 😄
=> Add o3-mini to Copilot Adapter

lua/codecompanion/adapters/copilot.lua, lua/codecompanion/adapters/openai.lua
Add the [reasoning_effort](https://platform.openai.com/docs/api-reference/chat/create#chat-create-reasoning_effort) parameter to both Copilot and OpenAI adapters.
This also updates the Copilot adapter to point to a versioned model of `o3-mini`.
=> feat(adapters): add reasoning effort to copilot and openai

lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/strategies/cmd.lua, lua/codecompanion/strategies/inline/init.lua
Add more detail to the event payload. Output will now be something like:
```lua
{
buf = 3,
data = {
adapter = {
formatted_name = "Copilot",
model = "o3-mini-2025-01-31",
name = "copilot"
},
bufnr = 3,
strategy = "chat" -- "inline" | "cmd"
},
event = "User",
file = "CodeCompanionRequestStarted",
group = 13,
id = 29,
match = "CodeCompanionRequestStarted"
}
```
#813
=> feat(events): add strategy and adapter to payload

lua/codecompanion/strategies/chat/ui.lua
We can now define both a custom title for the chat window and a higlight group by doing something like:
```lua
window = {
title = { { 'CodeCompanion', 'TelescopeTitle' } },
```
https://github.com/olimorris/codecompanion.nvim/discussions/815
=> Make ui chat title configurable

lua/codecompanion/adapters/non_llm/jina.lua, lua/codecompanion/http.lua
Some models may not have a `schema.model.default` value so we need to check against that in the `http.lua` file.
=> fix(http): prevent model from no schema.model

lua/codecompanion/strategies/chat/slash_commands/init.lua
Allows for a user to have:
```lua
["mycmd"] = {
description = "describe what mycmd inserts",
callback = function(chat)
return chat:add_buf_message({ content = "My custom command" })
end,
opts = {
contains_code = true
}
}
```
in their config instead of pointing to a lua module.
=> feat(slash_cmds): can be functions and modules

doc/getting-started.md
Updated the documentation to clearly explain how users can send prompts in the chat buffer. Specified that `<C-s>` works in insert mode and `<CR>` in normal mode for better readability.
N/A
N/A
=> docs: clarify chat buffer prompt submission methods

lua/codecompanion/providers/diff/default.lua
When closed, a diff buffer still exists (it's just hidden and unlisted). It also keeps "diffthis" set. This can lead to complicated and confusing diffs as the number of dangling buffers increases.
Since diff buffers are temporary and not re-used it should be safe to delete them instead of closing them.
- Fixes #851
=> fix: delete diff buffers instead of closing

README.md, doc/codecompanion.txt, doc/index.md, lua/codecompanion/adapters/githubmodels.lua, lua/codecompanion/config.lua
GitHub Models and GitHub Copilot seems to be two different things: e.g. you can use Codestral-2501 via GitHub models, but not Copilot, but from other side Claude 3.5 Sonnet and Gemini 2.0 Flash is available only via Copilot. This adds support for GitHub Models.
Result of this discussion: https://github.com/olimorris/codecompanion.nvim/discussions/859
=> GitHub Models support (new adapter)

doc/extending/prompts.md
Update code block to correctly pass buffer number.
- [] I've updated the README and/or relevant docs pages
=> Fix typo in doc/extending/prompts.md.

doc/usage/events.md, lua/codecompanion/http.lua
Once a request starts streaming, `CodeCompanionRequestStreaming` will be fired with the following payload:
```lua
{
buf = 10,
data = {
adapter = {
formatted_name = "Copilot",
model = "gpt-4o-2024-08-06",
name = "copilot"
},
bufnr = 10,
id = 972808,
strategy = "chat"
},
event = "User",
file = "CodeCompanionRequestStreaming",
group = 13,
id = 29,
match = "CodeCompanionRequestStreaming"
}
```
As discussed in #875
=> feat(events): new request streaming event

lua/codecompanion/strategies/chat/slash_commands/file.lua, tests/strategies/chat/test_references.lua
On the references object in the chat buffer, the full path is always used for a file. But the relative path is displayed in the chat buffer. This caused a mismatch when re-sending a pinned file's contents.
#889
=> Fix pinned file references

lua/codecompanion/strategies/chat/slash_commands/fetch.lua, lua/codecompanion/strategies/chat/slash_commands/init.lua, lua/codecompanion/strategies/chat/slash_commands/workspace.lua
- Previously, if a user attempted to restore a url from a cache and it didn't exist then an error would be throw
- Workspace descriptions were not added to the URLs
=> fix(workspaces): add description to urls from cache

lua/codecompanion/strategies/chat/init.lua
`v12.0.0` introduced more explicit Tree-sitter queries which extracted the user's role from the H2 header in the chat buffer, without any of the `##`. This failed to account for if users had `config.display.chat.show_header_separator` turned on, which in most cases would have added an ` -` to the end of the role. This fix accounts for that.
#887 #899
=> fix(chat): header separator is now detected

doc/configuration/chat-buffer.md, lua/codecompanion/strategies/chat/tools/init.lua
This allows the tool to be "configured" before being loaded by codecompanion. It makes it easier for plugin devs to provide integrations with codecompanion.
- Fixes #931 
Before this PR you have to put the tool in a `lua/codecompanion/my_plugin/tool.lua` and use it as:
```lua
agents = {
tools = {
my_plugin = {
callback = "my_plugin.tool"
},
}
}
```
Now you can do 
```lua
agents = {
tools = {
my_plugin = {
callback = require("my_plugin").make_tool(opts)
},
}
}
```
where `opts` can contain parameters to set up the tool.
=> feat(tools): allow passing a table as the `callback` of a tool.

lua/codecompanion/adapters/anthropic.lua, lua/codecompanion/adapters/gemini.lua, lua/codecompanion/adapters/ollama.lua, lua/codecompanion/adapters/openai.lua, lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/strategies/inline/init.lua, tests/adapters/test_ollama.lua, tests/strategies/inline/test_inline.lua
The Ollama model allows `schema.models.default` and `schema.models.choices` to be functions. Without caching, during the same request, this is potentially "expensive" as the adapter class has to resolve them.
The `handlers.on_exit` function is the ideal place to reset the cache however it's only called when the request ends completely. If the user cancels the request then previously it was not called.
This PR fixes the above and also streamlines Ollama's `inline_output` method.
=> Ollama - Fix inline output parsing and adapter caching

lua/codecompanion/strategies/chat/tools/init.lua
I noticed when asking the LLM to run a command, my `cargo build` errors weren't being logged and instead the response was:
> There was an error from the command `cargo build`:
> 
> ```txt
> Tool failed with code 101 and no output
> ```
With this change, the error is correctly captured and added to the prompt:
> There was an error from the command `cargo build`:
> 
> ```txt
> bunch of stderr output here...
> ```
This might not be the correct way to solve the issue, but in the logs I always see the `err` variable as `nil`, and Plenary docs aren't very helpful on understanding what the variable represents. Feel free to close this and solve it the proper way, but this _worked on my machine_.
=> make stderr capturing work for "streaming" job output

lua/codecompanion/strategies/chat/tools/init.lua
Previously, command tools did not follow the [FIFO](https://en.wikipedia.org/wiki/FIFO_(computing_and_electronics) method. Instead, it was determined based on runtime.
This caused issues if you had heavy I/O commands (via the `@files`) tool or were installing packages (via the `@cmd_runner`) tool. Now we use the plenary method `and_then_wrap` to ensure that commands are sequenced correctly, based on the order in which the LLM requests them.
Unfortunately, there seems to be a bug in how `vim.fn.confirm` is handling these multi-chain approaches.
=> fix(tools): can now chain jobs effectively

lua/codecompanion/strategies/inline/init.lua
Gemini is marvellous to talk to and a pain in the backside to program with. Instead of returning the placement in lower case like every LLM, it likes to capitalise it...
=> fix(inline): ensure placement is in lower case

lua/codecompanion/strategies/chat/tools/init.lua
Currently, the tool class discard `stdout` when `stderr` is not empty even if the exit code is 0. In the real world a lot of programs/libraries (in my case, [VectorCode](https://github.com/Davidyz/VectorCode/wiki/Neovim-Integrations#tool)) use `stderr` for warnings that don't actually terminate the command. The current way in which `stdout` and `stderr` are handled caused false negatives in some cases (outputs with useful information get thrown away).
> I'm not sure if it's appropriate to call both `output.error` and `output.success`. I simply copied the code under `elseif not vim.tbl_isempty(stdout) then` here.
=> feat(chat): when `stderr` is not empty, do not discard `stdout` when exit code is 0

doc/configuration/chat-buffer.md, lua/codecompanion/strategies/chat/init.lua
Previously if users were trying to add a reference to the chat buffer, it involved two method calls. Now users can use `chat:add_reference`.
=> feat(chat): easier to add refs from external sources

lua/codecompanion/strategies/chat/tools/files.lua, tests/strategies/chat/tools/test_files.lua
Previously, the return values of `gsub` were passed to `p:write`. This is incorrect because `gsub` returns two values: the changed data and the number of substitutions made. Since the method signature for `write` is `write(txt, flag, mode)`, the number of substitutions returned by `gsub` was incorrectly passed as the flag attribute. This could lead to incorrect behavior.
Passing `"w"` explicitly means that the file will be opened for writing, and if it has any content, it will be truncated.
I also modified the test so that it would fail with the previous implementation. The reason for the failure is that when invoking `write` with the changed text and a flag of 1 (1 is the number of substitutions returned by gsub, and by accident it also corresponds to the O_WRONLY flag), the file is not …
=> fix(chat): add missing write flag attribute when editing files

lua/codecompanion/strategies/init.lua
When a workflow contains references, they are now properly processed using the add_ref function.
Actually it's just a Q&A discussion: https://github.com/olimorris/codecompanion.nvim/discussions/957
=> Add reference handling to workflow processing

lua/codecompanion/http.lua, tests/test_http.lua
Pass adapter.raw through adapter:set_env_vars() to enable variable substitution.
Also appends adapter.raw to the static raw arguments defined in the http client.
Implements the change discussed in #974 that makes it easier to write an adapter for AWS Bedrock Anthropic models.
Tested with my custom Bedrock adapter, as well as a built-in adapter (deepseek).
=> fix(adapter): variable substitution in 'raw'.

lua/codecompanion/strategies/inline/init.lua
Refactors some of the logic around checking the LLMs output in response to an inline prompt.
=> refactor(inline): re-structure error checking

lua/codecompanion/adapters/init.lua
Previously the adapter would error if a function returned a number, because it was trying to do variable replacement on it.
=> fix(adapters): only try and replace str variables

lua/codecompanion/adapters/copilot.lua
If you've enabled Claude 3.7-sonnet in your GitHub settings, you can now use this with the Copilot adapter.
I've not added in any reasoning parameters for this. Just the model.
=> feat(adapters): add claude-3.7-sonnet to copilot

lua/codecompanion/adapters/ollama.lua
Currently the `get_models` function in the Ollama adapter forces users to use  `Bearer` in the authorization header if an api key exists.
#976
=> fix(ollama): allow users to customize the authorization header in `get_models`

doc/codecompanion.txt, lua/codecompanion/adapters/anthropic.lua, lua/codecompanion/strategies/chat/init.lua
Claude 3.7 adds DeepSeek R1-like 'extended thinking' - see https://www.anthropic.com/news/visible-extended-thinking
This PR adds support for this, and also [extended output](https://docs.anthropic.com/en/docs/about-claude/models/extended-thinking-models#extended-output-capabilities-beta).
Like the DeepSeek plugin, it outputs the 'thinking' text when streaming.
One thing I'd appreciate feedback on. I've added parameters that don't directly map to API parameters, which I then set to nil later once we've built the actual params/header required. Is there a better way to do this?
=> Add Extended Thinking and Extended Output for Claude 3.7

lua/codecompanion/adapters/copilot.lua
From discussion #858
https://github.com/olimorris/codecompanion.nvim/discussions/858#discussioncomment-12311109
During the development of this feature I was able to access "claude-3.7". Now I can no longer access claude 3.7 in vscode. Maybe they have [restricted the access](https://github.blog/changelog/2025-02-24-claude-3-7-sonnet-is-now-available-in-github-copilot-in-public-preview/)? (im on student plan)
=> feat(copilot): get available models from copilot endpoint

lua/codecompanion/adapters/copilot.lua, lua/codecompanion/strategies/inline/init.lua
Getting models dynamically in the Copilot adapter was leading us to overwrite the `opts.stream` variable in the adapter itself. This meant that `inline_output` couldn't be called.
#1036
=> fix(adapters): inline editing with copilot

doc/extending/adapters.md, lua/codecompanion/adapters/anthropic.lua, lua/codecompanion/adapters/azure_openai.lua, lua/codecompanion/adapters/copilot.lua, lua/codecompanion/adapters/deepseek.lua, lua/codecompanion/adapters/gemini.lua, lua/codecompanion/adapters/githubmodels.lua, lua/codecompanion/adapters/huggingface.lua, lua/codecompanion/adapters/init.lua, lua/codecompanion/adapters/ollama.lua, lua/codecompanion/adapters/openai.lua, lua/codecompanion/adapters/openai_compatible.lua, lua/codecompanion/adapters/xai.lua, lua/codecompanion/http.lua, lua/codecompanion/schema.lua, lua/codecompanion/strategies/chat/debug.lua, lua/codecompanion/strategies/chat/init.lua, tests/adapters/test_anthropic.lua
`schema.*.condition` previously only received the `CodeCompanion.Schema` as a parameter which put it at odds with `schema.*.default` which received `CodeCompanion.Adapter`. Previously, this worked fine. However, with the advent of reasoning models, different schema structures are required for different models. This PR makes it easier to control what schema is displayed to the user and therefore what can be edited as part of the request.
This PR also adds types to the schema values.
=> refactor adapter `condition` and add schema types

lua/codecompanion/http.lua
Variables are overwritten in the adapter, permanently. This results in adapters like Copilot, which need to regularly update their environment with a token, holding expired information. This PR addresses this by ensuring any variable replacement is done on a copy of the adapter rather than the adapter itself.
#1052
=> fix(adapters): overwriting of vars

lua/codecompanion/strategies/chat/slash_commands/fetch.lua
Following my comment here https://github.com/olimorris/codecompanion.nvim/issues/948#issuecomment-2667153570 I've added a space to the fetch input message. Before and after images follow
=> fix: add space to fetch ui input message

doc/configuration/chat-buffer.md, lua/codecompanion/strategies/chat/agents/init.lua
* Tool callback can now be a function which enables lazy loading of any modules that return tool schemas and also mitigates any errors due to some plugin not loaded to the runtime by the time `codecompanion.setup` is called.
* Fixed incorrect documentation for configuring tools as the below doesn't return the `Tool` schema.
```lua
tools = {
["my_tool"] = {
description = "Run a custom task",
callback = function(command)
-- Perform the custom task here
return "Tool result"
end,
}
}
```
* Did not commit `make docs` changes as there were many updates non related to this commit which the author may run in a docs or chore commit later.
=> patch(agents): tool.callback can be a function and fixed tools config docs

lua/codecompanion/strategies/chat/references.lua
=> fix: header separator causing references not to be added to the chat

lua/codecompanion/config.lua
Claude 3.7 loves to use H1 and H2 headers in its response. The impact of this is it measures with the visuals and navigation in the chat buffer.
=> fix(chat): update system prompt to avoid using h1 and h2 headers

doc/configuration/chat-buffer.md, lua/codecompanion/config.lua, lua/codecompanion/strategies/chat/init.lua
When the response is long, it just scrolls up away while reading.
Add a flag to control this behavior. 
It's on by default to prevent introducing changes.
Turn it off explicitly if annoyed.
=> Add flag `display.chat.follow`

doc/extending/tools.md, lua/codecompanion/strategies/chat/agents/executor/func.lua
The documentation has an error on the return type of function-based tools. See the patch for details.
I also included the type annotation to the executor.
=> docs(tools): update documentation on function-based tool return type.

lua/codecompanion/strategies/chat/agents/executor/init.lua
…values (numbers) to be used.
The changes in #1104 means that only `string` and `table` are allowed for `output`, which breaks the calculator tool demo from the documentation. 
Fix an issue introduced by #1104
=> fix(func_tool): allow non-table values (numbers) to be passed.

lua/codecompanion/strategies/init.lua
System prompts are now hidden by default in the chat
=> feat(chat): hide system prompts by default

doc/extending/tools.md, lua/codecompanion/strategies/chat/agents/executor/func.lua, tests/config.lua, tests/strategies/chat/agents/executor/test_queue_async.lua, tests/strategies/chat/agents/tools/stubs/func_async_1.lua, tests/strategies/chat/agents/tools/stubs/func_async_2.lua, tests/strategies/chat/agents/tools/stubs/xml/async_queue_xml.lua, tests/strategies/chat/agents/tools/stubs/xml/mixed_queue_xml.lua
This PR implements a `output_handler` parameter for the function tool, which can be called by an async callback used in the function tool body.
Discussed in #1103 
Previously a function-based tool has the following signature:
```
fun(agent, actions, input): {status: "success"|"error", data: any}
```
This PR introduces a 4th parameter, `output_handler`, which invokes the `executor:success` or `executor:error`. This allows users to build async function tools without blocking the UI. Example:
```lua
cmds = {
function(agent, actions, input, output_handler)
-- this is for demonstration only
vim.lsp.client.request(lsp_method, lsp_param, function(err, result, _, _)
output_handler({status = "success", data = result})
end, buf_nr)
end
}
```
I tested this with the calculator demo (as a synchronous …
=> feat(tool): implement a callback for async function-based tool.

lua/codecompanion/config.lua
This adds Mistral to the `config.lua` file so users can leverage it easily in their config.
=> fix(adapters): add mistral to the config

lua/codecompanion/adapters/copilot.lua
When switching adapters to the Copilot adapter, the user would encounter an unauthorized token error after 25 minutes. This was due to the bearer token being hard-coded in the header when the `get_models` function was called.
#1149
=> fix(adapters): copilot token issue when changing adapter

lua/codecompanion/adapters/ollama.lua
ollama remove option `tfs_z`
https://github.com/ollama/ollama/pull/8515
Ollama warn log:
```
level=WARN source=types.go:522 msg="invalid option provided" option=tfs_z
```
https://github.com/olimorris/codecompanion.nvim/discussions/1151
=> fix(ollama): remove option `tfs_z`

lua/codecompanion/strategies/chat/variables/user.lua, lua/codecompanion/strategies/inline/variables/init.lua
inline variables can be functions, chat variable function callbacks gets self
CodeCompanion.Inline.Variable config.callback can be a function. This function will have a single argument i.e CodeCompanion.Inline.Variable
CodeCompanion.Variable.User config.function callback will receive a single argument i.e CodeCompanion.Variable.User
=> fix: (#1175) 

lua/codecompanion/providers/completion/blink/init.lua
When using blink.cmp cursor was not correctly set up after selecting an option
https://github.com/olimorris/codecompanion.nvim/issues/1159
=> fix(blink): cursor put at wrong position after accepting

lua/codecompanion/adapters/gemini.lua
Google recently released their Gemini 2.5 pro model. Simply adding it as an option to the gemini adapter.
=> Add gemini 2.5 pro option to gemini adapter

queries/java/symbols.scm
Adds the Treesitter symbol queries for Java from [Aerial](https://github.com/stevearc/aerial.nvim/blob/master/queries/java/aerial.scm).
N/A
N/A
=> feat(symbols): add symbols for Java

lua/codecompanion/adapters/gemini.lua, tests/adapters/stubs/gemini_no_streaming.txt, tests/adapters/stubs/gemini_streaming.txt, tests/adapters/test_gemini.lua
Gemini now has an [OpenAI compatible endpoint](https://ai.google.dev/gemini-api/docs/openai#rest). This means we can move away from their hideous default and reuse the OpenAI adapter. It also paves the way for easier tool use in the function calling PR.
=> refactor: move Gemini to OpenAI endpoint

lua/codecompanion/strategies/chat/ui.lua
opts.visible is not respected for non-"system" roles in chat.
- Fixes #1203
=> fix(ui): respect opts.visible for non-"system" roles

lua/codecompanion/strategies/chat/agents/init.lua
system_prompt of tools.groups being a function makes it dynamic and the following possible.
```lua
groups = {
mcp = {
description = "MCP Servers Tool",
system_prompt = function(_)
-- get the running hub instance
local hub = require("mcphub").get_hub_instance()
return hub:get_active_servers_prompt() -- generates prompt from currently running mcp servers
end,
tools = {"use_mcp_tool","access_mcp_resource"},
},
},
```
=> fix(agents): system_prompt in tools.groups can be a function

lua/codecompanion/strategies/chat/ui.lua
This fixes my comment in https://github.com/olimorris/codecompanion.nvim/issues/959#issuecomment-2694619521
Basically if the user prompt content is empty we don't set the trimempty flag which allows to have an empty line between the user role (Me) and the actual content.
=> Don't trim empty lines with user role and empty content

lua/codecompanion/providers/actions/telescope.lua
This is a followup to #1195. 
Before:
After:
=> Use markdown ft and respect blank lines in Telescope action palette

lua/codecompanion/strategies/chat/agents/tools/files.lua
This is the make the @files tool's prompt more accurate: updating prompt to say that the xml schema is provided below and to respect the tags accurately.
The @files tool failed few times whereas the other tools don't fail for me.
Upon investigation , in one instance, the LLM didn't respect the schema exactly and used `<content>` instead of `<contents>`.
Other tools such as @editor has an explicit section called [XML schema](https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/strategies/chat/agents/tools/editor.lua#L287) whereas with @files it doesn't explicitly say it, that might be the reason.
=> fix(files tool): be more explicit about the xml schema

lua/codecompanion/strategies/chat/references.lua, lua/codecompanion/types.lua, tests/strategies/chat/test_references.lua
This PR allows certain references to be hidden from the chat buffer. This is useful for tools/slash commands that add _a lot_ of references to the chat buffer.
Reference providers (tool, slash command, variable, etc.) can use the `visible` option to choose whether it should be shown in the chat UI:
```lua
agent.chat.references:add({
source = "tool",
id = "ref_id",
opts = { visible = false },
})
```
The value for the `visible` key falls back to `config.display.chat.show_references`, so it should respect existing configurations.
See [here](https://github.com/Davidyz/VectorCode/pull/72#issuecomment-2799884579).
=> feat: allow toggling the visibility of individual references.

lua/codecompanion/strategies/chat/slash_commands/buffer.lua, lua/codecompanion/strategies/chat/slash_commands/file.lua, lua/codecompanion/strategies/chat/slash_commands/help.lua, lua/codecompanion/strategies/chat/slash_commands/symbols.lua
The default Snacks.picker options requires the main window to be a file (leading to the behavior in the referenced issue) but this can be configured.
Fixes #971
=> fix(slash_cmds): focus on chat window after closing snacks picker

lua/codecompanion/strategies/inline/init.lua
This pull request adds `context` to the `InlineStarted` data payload event, primarily to retrieve `start_line` and `end_line`. This enables the creation of various extmarks, such as status column icons, virtual text, etc.
Here is a simple example of extmarks added to add status column icon when the `InlineStarted` event is triggered and cleared at the `InlineFinished` event.
=> feat(events): add context to InlineStarted event data payload

lua/codecompanion/completion.lua
Tools can be hidden from cmp menu when they are from a group. 
Useful in cases where tools in a group can't be used individually as there is no separate system_prompt for each tool but only for the combined group.
E.g `@mcp` group provides the system_prompt for both tools. Individual `use_mcp_tool` and `access_mcp_resource` have a empty system_prompt. Showing these in the cmp might lead to user just using `@use_mcp_tool` rather than `@mcp` group. Ability to hide them with `visible = false` avoids this.
=> feat: tools can be hidden from cmp menu when they are from a group

lua/codecompanion/strategies/chat/init.lua
Allow users to submit blank messages to the LLM, but only if they have at least one message in the chat history.
=> refactor(chat): better handling of blank messages

lua/codecompanion/strategies/chat/init.lua
Set `auto_submit_success` or `auto_submit_errors` and use some tool. It fails with "Bad Request" error.
With `auto_submit_success` and `auto_submit_error` the request fails with "Bad Request". 
The Bad Request is raised due to tools field not present in the request body json file when auto sending the request after a tool call. Having a tool_call_id or role = tool and not having the tools field might be the cause.
The tools are being removed in the below code by comparing them with refs from the chat. This leads to all tools being removed as refs might not be rendered in the chat when in auto_submitting.
```lua
---Reconcile the references table to the references in the chat buffer
---@return nil
function Chat:check_references()
local refs = self.references:get_from_chat()
if …
```
=> fix: don't remove tools by checking chat refs while auto_submitting

lua/codecompanion/strategies/chat/ui.lua
This addresses my second comment https://github.com/olimorris/codecompanion.nvim/issues/959#issuecomment-2694619521 by adding a blank line between the system role content and the user role heading.
=> Add blank line before user role

doc/extensions/vectorcode.md
Add VectorCode to the extensions section in the documentation.
N/A
[test](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md#testing) coverage for this fix/feature
=> docs(extension): add vectorcode extension page

lua/codecompanion/strategies/chat/references.lua, tests/strategies/chat/test_references.lua
I was unable to hide references even if I added them with `opts = {visible = false}`.
Specifically, the extra test I added in this PR fails without this patch.
[test](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md#testing) coverage for this fix/feature
=> fix(reference): make sure ref with `opts.visible = false` are hidden.

lua/codecompanion/strategies/inline/init.lua
placement new should not create diffs views in neovim
This pull request fix an issue when placement "new" create a diffview in neovim. This cause the following error to happen:
```
Error executing vim.schedule lua callback: ...panion.nvim/lua/codecompanion/providers/diff/default.lua:79:
Cursor position outside buffer
[C]: in function 'nvim_win_set_cursor'
...panion.nvim/lua/codecompanion/providers/diff/default.lua:79: in function 'new'
...panion.nvim/lua/codecompanion/strategies/inline/init.lua:720: in function 'start_diff'
...panion.nvim/lua/codecompanion/strategies/inline/init.lua:468: in function <...panion.nvim/lua/codecompanion/strategies/inline/init.lua:467>
```
https://github.com/olimorris/codecompanion.nvim/issues/1308 …
=> fix(inline): added check for placement "new"

lua/codecompanion/strategies/chat/agents/executor/init.lua
Replace `vim.fn.confirm` with `vim.ui.select`, this will improve the UI experience when using function tool calling!
=> feat: replace `vim.fn.confirm` with `vim.ui.select`

lua/codecompanion/strategies/chat/init.lua, tests/strategies/chat/test_references.lua
Sometimes there can be double references appearing in the chat buffer.
=> fix(chat): prevent double references in the chat buffer

lua/codecompanion/strategies/chat/init.lua, tests/expectations.lua, tests/strategies/chat/test_references.lua
As discussed in #1336, when tools are deleted as references, this causes an error as the tool schema table goes from a dictionary to an array. This PR corrects that.
=> fix(tools): tools can now be deleted as references

lua/codecompanion/providers/completion/cmp/models.lua, lua/codecompanion/strategies/chat/init.lua, tests/test_strategies.lua
As we get more community extensions, they will be making use of the chat buffers public methods. This refactor reduces the amount of public methods to tighten scope and make future refactors less troublesome.
=> refactor(chat): make some public methods private

CHANGELOG.md, lua/codecompanion/strategies/chat/slash_commands/buffer.lua, lua/codecompanion/strategies/chat/slash_commands/file.lua, lua/codecompanion/strategies/chat/slash_commands/help.lua, lua/codecompanion/strategies/chat/slash_commands/symbols.lua
I noticed that after #1248 I was still seeing issue #971. It seems that this is because I was using the float layout and there is another option to set if the chat window is a floating window:
https://github.com/folke/snacks.nvim/blob/bc0630e43be5699bb94dadc302c0d21615421d93/lua/snacks/picker/core/main.lua#L8
I think this is comes under straightforward bug fix so no prior discussion
- Fixes #971 for floating windows
=> Minor fix to focus on floating chat windows after closing snacks picker

doc/codecompanion.txt, doc/usage/chat-buffer/agents.md, doc/usage/introduction.md, lua/codecompanion/strategies/chat/agents/init.lua
Previously, if my prompt was:
`I want to test the @mcp tools. What should we test first?`
The LLM receives:
`I want to test the  tools. What should we test first?`
When really it should receive:
`I want to test the access_mcp_resource, use_mcp_tool tools. What should we test first?`
=> fix(tools): tool groups are replaced properly in the chat buffer

lua/codecompanion/strategies/chat/agents/executor/init.lua
In the previous 1e2f69a9a65bd716cf897393e7af65fc74907ed8 commit, self.subscribers:process was removed without corresponding call in the ready_chat_buffer. 
This PR process all subscribers in the ready_chat_buffer.
=> fix: call all subscribers on getting llm response

doc/configuration/adapters.md, lua/codecompanion/config.lua, lua/codecompanion/strategies/chat/keymaps.lua
Hi! This tries to have an easier way of switching between models by having a config option that automatically chooses the default model rather than displaying all available model choices (which we briefly discussed here https://github.com/olimorris/codecompanion.nvim/discussions/873#discussioncomment-12105260). 
Dunno if this is the best  (or even the proper way) of doing it though.
=> Allow to automatically choose default model when switching adapters

lua/codecompanion/strategies/chat/init.lua
If tools weren't used in a chat, the chat buffer was setting the tools table as a boolean rather than an empty table.
#1371
=> fix(chat): tools should be empty table if not used

lua/codecompanion/providers/init.lua
Disclaimer: Lua newbie here
I think we want diff to default to `mini_diff`/`mini.diff` when the latter  is available on the path. As is, this fails for me, and the attached patch fixes it.
=> fix(diff): use mini_diff default if mini.diff is available

lua/codecompanion/strategies/chat/agents/executor/init.lua, lua/codecompanion/strategies/chat/init.lua
With changes in #1348, subscribers in workflows would not result in references not being rendered. This was caused by issues in the timing of when the code was executed.
=> fix(workflows): ensure references are rendered

lua/codecompanion/adapters/openai.lua
Another instance of DeepSeek deviating from the OpenAI API format.
#1378
=> fix(openai): do not send empty tools array

doc/codecompanion.txt, doc/configuration/action-palette.md, doc/getting-started.md, lua/codecompanion/config.lua, lua/codecompanion/providers/actions/snacks.lua, lua/codecompanion/providers/init.lua
Adding [snacks.nvim](https://github.com/folke/snacks.nvim) as an action provider.
#1255
=> Add Snacks as actions provider

doc/codecompanion.txt, doc/extensions/history.md
This PR adds [history extension](https://github.com/ravitemer/codecompanion-history.nvim) to community extensions. 
- 💾 Automatic chat session saving with context preservation
- 🎯 Smart title generation for chats 
- 🔄 Continue from where you left
- 📚 Browse saved chats with preview
- 🔍 Multiple picker interfaces
- ⚡ Restore chat sessions with full context and tools state
https://github.com/user-attachments/assets/04a6ad1f-8351-4381-ae60-00c352a1670c
=> docs: add history extension to community extensions

doc/codecompanion.txt, doc/extensions/history.md
This PR updates the History extension with new additional configuration.
This includes more flexible chat saving options by adding configurable auto-save behavior and manual save functionality. Users now have better control over when their chats are saved.
- ✨ **Configurable Auto-Save**: 
- New `auto_save` option (default: true) to enable/disable automatic saving
- When enabled, saves chat state after each message and LLM response
- When disabled, relies on manual saving only
- 🔑 **Manual Save Functionality**:
- New `save_chat_keymap` option (default: "sc") for manual saving
- Allows saving chat state on-demand regardless of auto-save setting
- Works consistently in both auto-save enabled and disabled modes
- Added new configuration options:
```lua
opts = {
-- Save all chats by default …
```
=> docs: update history extension with new features

lua/codecompanion/adapters/deepseek.lua
I failed to check that the tools table existed on the DeepSeek adapter.
#1405
=> fix(deepseek): inline prompt to chat causes error

lua/codecompanion/strategies/chat/agents/init.lua, tests/strategies/chat/agents/test_agents.lua
When LLM calls a tool that is missing, subsequent prompts fail with `Bad Request` error due to missing message with `tool` role. 
To address this we return the error mentioning that the tool is not found along providing it the available_tools as tool call response, so that on next prompts LLM corrects the tool call.
=> Better handle missing tools

doc/codecompanion.txt, doc/configuration/adapters.md, lua/codecompanion/adapters/init.lua, lua/codecompanion/strategies/chat/init.lua, tests/test_adapter.lua
Add some helper methods to enable users to access models more easily on adapters.
=> refactor: add adapter.model and adapter.model.opts to schema

doc/codecompanion.txt, doc/configuration/chat-buffer.md, lua/codecompanion/strategies/chat/helpers.lua, lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/strategies/chat/slash_commands/keymaps.lua, tests/config.lua, tests/strategies/chat/slash_commands/test_keymaps.lua
This feature allows users to call slash commands via keymaps, in the chat buffer.
=> feat(chat): call slash commands with keymaps

lua/codecompanion/adapters/init.lua
#1403 introduced some helper functions to enable users to more easily access the current model. However, if the model is a function this caused a stack overflow. This PR stops the executing of this function.
#1415
=> fix(adapters): stack overflow if default model is function

doc/extensions/history.md
* Add expiration_days to auto delete chats once expired (default 0 disabled)
* Allow renaming chats
* Add insert mode mapping for pickers
=> docs: update history extension documentation

lua/codecompanion/strategies/inline/init.lua
=> fix(inline): don't modify prompts going to the chat buffer

lua/codecompanion/adapters/gemini.lua
This basically addresses my comments here https://github.com/olimorris/codecompanion.nvim/discussions/1337#discussion-8269597
1. Since the gemini adapter uses the openai endpoint then trying to pass parameters as
```lua
gemini_flash = function()
return adapters.extend('gemini', {
env = { api_key = GEMINI_API_KEY },
schema = {
model = { default = 'gemini-2.5-flash-preview-04-17' },
maxOutputTokens = { default = 2048 },
},
})
end,
```
obviously would not work since the Openai API expects `max_tokens` rather than `maxOutputTokens`.
2. Added a new `reasoning_effort` parameter that allows to turn thinking off for the flash model as per https://ai.google.dev/gemini-api/docs/openai#thinking
=> Allow to override gemini parameters and add reasoning effort

lua/codecompanion/providers/slash_commands/default.lua, lua/codecompanion/strategies/chat/agents/executor/init.lua, lua/codecompanion/strategies/chat/slash_commands/fetch.lua, lua/codecompanion/strategies/chat/slash_commands/help.lua, lua/codecompanion/strategies/chat/slash_commands/workspace.lua
To ease picker customization, this PR adds the `kind` option to all usages of `vim.ui.select`.
=> fix: include `kind` option in all `vim.ui.select` calls

doc/codecompanion.txt, lua/codecompanion/adapters/init.lua
Related this issue comment: https://github.com/ravitemer/codecompanion-history.nvim/issues/9#issuecomment-2885801123
When user declares some custom adapters like below, 
```lua
return {
adapters = {
openrouter = function()
return require("codecompanion.adapters").extend("openai_compatible", {
env = {
url = "https://openrouter.ai/api",
api_key = "OPENROUTER_API_KEY",
chat_url = "/v1/chat/completions",
},
schema = {
model = {
default = "google/gemini-2.5-flash-preview",
},
},
})
end,
},
}
```
With `Chat:new()` the adapter is resolved. But the `adapter.name` will be `openai_compatible` instead of `openrouter`. Most users don't provide name or provide a different name from the `config.adapters.[adapter_name]`. This leads to an issue when we need to restore the chat with the saved adapter …
=> fix: user-extended adapters inheriting name

lua/codecompanion/adapters/init.lua
Fixes bug as commented in https://github.com/olimorris/codecompanion.nvim/pull/1459#issuecomment-2892619215
- [] I've updated the README and/or relevant docs pages
=> fix: adapters.resolve not using custom adapter, bug introduced with (#1459)

lua/codecompanion/adapters/copilot.lua
Per:
https://github.blog/changelog/2025-05-08-openai-gpt-4-1-is-now-generally-available-in-github-copilot-as-the-new-default-model/
Recently switched in CopilotChat:
https://github.com/CopilotC-Nvim/CopilotChat.nvim/commit/5f105cf2453585487d3c9ccfe7fd129d3344056c
=> Switch to new default Copilot model

lua/codecompanion/config.lua, lua/codecompanion/providers/init.lua
- Introduce `ProviderSpec` and `Providers` types to define provider configurations.
- Add a unified `find_provider` function to handle provider selection based on availability and optional conditions.
- Refactor all provider selection functions (`action_palette_providers`, `diff_providers`, `help_providers`, `pick_providers`) to use the new logic, improving maintainability and extensibility.
- Improve logic for selecting Snacks as a provider
None, but key highligh is, as a part of the refactor it improve picker selection specially in case of `Snacks`. It is possible that picker might be disable and we should respect that.
=> refactor(providers): centralize provider selection logic

lua/codecompanion/strategies/inline/keymaps.lua
Allows to add keymaps in visual mode for accept and reject changes.
Fixes an error if a visual mode mapping is added to the inline strategy.
Example: 
```lua
inline = {
keymaps = {
accept_change = {
modes = {
n = "<C-a>",
x = "<C-a>"
}
},
reject_change = {
modes = {
n = "<C-r>",
x = "<C-r>"
}
}
}
},
```
Error: 
```lua
Error  E5108: Error executing lua: vim/keymap.lua:0: E31: No such mapping
[C]: in function 'nvim_buf_del_keymap'
vim/keymap.lua: in function 'del'
...ion.nvim/lua/codecompanion/strategies/inline/keymaps.lua:13: in function 'clear_map'
...ion.nvim/lua/codecompanion/strategies/inline/keymaps.lua:35: in function 'rhs'
...y/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:80: in function <...y/codecompanion.nvim/lua/codecompanion/utils/keymaps.lua:77>
```
=> fix(inline): keymap modes

lua/codecompanion/adapters/init.lua, lua/codecompanion/http.lua
Allows the adapter to implement a custom request protocol by overriding `Client:request`. Update the config to:
```lua
require("codecompanion").setup({
adapters = {
opts = {
---Send a HTTP request
---@param payload { messages: table, tools: table|nil } The payload to be sent to the endpoint
---@param actions CodeCompanion.Adapter.RequestActions
---@param opts? table Options that can be passed to the request
---@return table|nil The Plenary job
request = function(client, payload, actions, opts)
-- implement custom request logic here
end
},
}
})
```
Above is another attempt at overriding the default http request logic - let me know what you think.
Here are the prior attempts for reference:
- #1457
- #1426
=> set Adapter.opts.request to override Client.request

doc/extensions/history.md
Updates history extension docs with title generation customization options. Useful so that user can specify cheap and faster models for title generation. Fixes issues where thinking tags being present in the title
=> docs: update history extension with title generation customization opts

doc/installation.md, lua/codecompanion/providers/init.lua
If `mini.nvim` is installed CodeCompanion will try to use `mini.diff`, but it only works if `setup()` was called.
This changes the default so it's only used if initialized, and updates the docs to share how to use MiniDiff only with CodeCompanion.
- [-] I've updated `CodeCompanion.has` in the [init.lua](https://github.com/olimorris/codecompanion.nvim/blob/main/lua/codecompanion/init.lua#L239) file for my new feature
- [-] I've added [test](https://github.com/olimorris/codecompanion.nvim/blob/main/CONTRIBUTING.md#testing) coverage for this fix/feature
=> fix(providers): only use `mini.diff` if initialized

lua/codecompanion/strategies/chat/references.lua
I have this following code in mcphub codecompanion success handler.
```lua
if has_function_calling then
chat:add_tool_output(
tool,
text,
(user_msg or show_result_in_chat or is_error) and (user_msg or text)
or string.format("**`%s` Tool**: Successfully finished", action_name)
)
for _, image in ipairs(images) do
helpers.add_image(chat, image)
end
else
```
After adding tool output, If I try to add image, I get the following error:
```txt
  Error  05:06:46 msg_show.lua_error Error executing vim.schedule lua callback: ...on.nvim/lua/codecompanion/strategies/chat/references.lua:94: Buffer is not 'modifiable'
[C]: in function 'nvim_buf_set_lines'
...on.nvim/lua/codecompanion/strategies/chat/references.lua:94: in function 'add' …
```
=> fix: unlock buffer when adding reference after a tool output

lua/codecompanion/adapters/copilot.lua
In closer examination of the Copilot API in VS Code, I've tweaked the settings of the Copilot adapter.
=> refactor(adapters): copilot more closely matches vs code

lua/codecompanion/adapters/openai.lua
AFAICT the boolean was always set to false preventing vision feature to work with the openai adapter
=> fix openai vision support

lua/codecompanion/strategies/chat/slash_commands/fetch.lua
Fixes the reference to the adapter in the fetch slash command after #1279 was merged
=> fix(slash_commands): update adapter reference

lua/codecompanion/helpers/patches.lua, lua/codecompanion/strategies/chat/agents/tools/files.lua, tests/fixtures/files-diff-1.5.patch, tests/fixtures/files-output-1.5.html
This reverts the revert in commit dbb287e1302563286870e72674f0b907c6db14f2.
This fixes the conflicts while reverting the revert discussed [here](https://github.com/olimorris/codecompanion.nvim/pull/1494#issuecomment-2909053308).
Basically `score-based-diff-merges` was built on top of `split-files-patch`. Merging `split-files-patch` was not needed if we merged `score-based-diff-merges` directly :).
This PR fixes them.
=> Reapply "Score based diff merges" (#1501)

doc/codecompanion.txt, doc/configuration/adapters.md, doc/getting-started.md, lua/codecompanion/adapters/init.lua, lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/strategies/cmd.lua, lua/codecompanion/strategies/inline/init.lua, tests/config.lua, tests/test_adapter.lua
Before this PR, it was cumbersome for users to specify a different model for an adapter without creating a separate copy of an adapter.
=> feat(adapters): users can specify models for strategies

lua/codecompanion/adapters/copilot.lua
On our enterprise version of copilot, all requests other than authorization go to different server communicated by the `<auth_response>.endpoints.api` property.
This PR implements supporting the same endpoint redirection.
=> fix: support endpoint redirection in copilot

lua/codecompanion/init.lua, lua/codecompanion/strategies/chat/ui.lua
Sometimes i like to toggle the chat window to reference my code,
but the cursor is always pushed back to the bottom, wich means
that i am forced to get back to where i was everytime i toggle.
This behavior can get particularlly annoying as the buffer grows in size.
I've hadled that by adding the `display.chat.follow_on_toggle` field, that when 
disabled, will keep the cursor where it was when using `:CodeCompanionChat Toggle`.
Before (enabled)
After (disabled)
=> Disable follow on toggle

lua/codecompanion/adapters/copilot.lua
Now GitHub have fixed the `Internal Server Error` which affected inline prompting, we can change the default Copilot model.
Reference:
- #1520
- #1481 
- #1465
- #1432
=> feat(adapters): new copilot default is gpt-4.1

lua/codecompanion/providers/completion/coc/init.lua, lua/codecompanion/providers/completion/coc/setup.lua
* The first commit is a minimal fix of an error that slipped out from [feat(providers): provider for coc completion #1421](https://github.com/olimorris/codecompanion.nvim/pull/1421). Without this, slash commands for coc completion won't work!
* The second commit is my final refactor that I planned to include in [feat(providers): provider for coc completion #1421](https://github.com/olimorris/codecompanion.nvim/pull/1421), but it was merged earlier. It just moves relevant functions to `setup.lua` and improves file handling.
Feel free to merge both, or just the minimal fix. Thanks, and sorry for not communicating clearly [feat(providers): provider for coc completion #1421](https://github.com/olimorris/codecompanion.nvim/pull/1421).
Slash commands for coc copmletion.
=> fix(providers): forgotten registration of coc execute function

lua/codecompanion/config.lua, lua/codecompanion/strategies/chat/ui.lua, lua/codecompanion/utils/ui.lua
My vim workflow tends to rely a lot on the default split width behavior built into vim, and I found that the configuration of this plugin forces you to define a specific buffer/window width.
This is a quick pass at extending the existing configuration to allow a string value of `"auto"` to be passed to the window config that will disable the `vim.cmd("vertical resize " .. width)` call if the user sets `width` to auto. I kept the implementation as simple as possible for now since it doesn't really make sense as value for floating windows, so I fell back to 0.45 in those situations.
If this is something you're willing to accept, I can go ahead and add documentation if necessary, but figured this was a good spot to get a discussion going if it's something you're willing to accept.
| before | …
=> Allow CodeCompanion chat buffer to act like a normal buffer

lua/codecompanion/strategies/chat/keymaps.lua
Correct the order of arguments in the yank command
to properly utilize the user-defined register.
This fix ensures that the yank operation behaves
as expected in the chat strategy.
There were no tests associated with it.
=> fix(chat): correct yank command syntax in keymaps

doc/codecompanion.txt, doc/configuration/chat-buffer.md, lua/codecompanion/utils/keymaps.lua
Allow `opts` to keymap config option
I was a bit unsure where to potentially add the docs for this. Do you have any pointers on where you want it? I also wasn't able to run `make all` because I had some problems installing `pandoc`, but let's see if the pipeline succeeds.
I think the dedicated `description` option could be deprecated in favor or `opts.desc`, but it would be harsh to just remove it right away at least
Fixes https://github.com/olimorris/codecompanion.nvim/discussions/1537
=> feat(keymaps): support `:map-arguments` in keymaps

doc/usage/chat-buffer/agents.md, lua/codecompanion/strategies/chat/agents/init.lua
If you set `vim.g.codecompanion_auto_tool_mode` (or use `gta` in the chat buffer), the plugin will now automatically submit error and success messages to the LLM.
Originally proposed in #1231
=> feat(tools): auto_tool_mode now auto submits

lua/codecompanion/strategies/chat/slash_commands/fetch.lua
Previously, the "Cache" option was always shown in the selection menu, even when no cached files were available. Now, "Cache" is only included if there are cached files, improving the user experience and preventing invalid selections.
Personally I don't generally cache urls so this is a small QoL for me. Feel free to dismiss it :)
=> feat(fetch): only show "Cache" option if cached files exist

lua/codecompanion/strategies/chat/slash_commands/fetch.lua
This makes the error messages from the fetch command more explicit.
=> refactor(slash_commands): improve fetch error messages

lua/codecompanion/utils/ui.lua
https://neovim.io/doc/user/deprecated.html#vim.highlight
The `vim.hl` won't be available in versions older than 0.12. This PR fallbacks to `vim.highlight`.
```txt
Error detected while processing User Autocommands for "CodeCompanionAgent*":
Error executing lua callback: ...ubuntu/codecompanion.nvim/lua/codecompanion/utils/ui.lua:139: attempt to index field 'hl' (a nil value)
...ubuntu/codecompanion.nvim/lua/codecompanion/utils/ui.lua:139: in function 'show_buffer_notification'
...n.nvim/lua/codecompanion/strategies/chat/agents/init.lua:76: in function <...n.nvim/lua/codecompanion/strategies/chat/agents/init.lua:67>
[C]: in function 'nvim_exec_autocmds'
...untu/codecompanion.nvim/lua/codecompanion/utils/init.lua:10: in function 'fire' …
```
=> fix: fallback to vim.highlight for nvim <0.12

doc/configuration/chat-buffer.md, lua/codecompanion/config.lua, lua/codecompanion/strategies/chat/agents/init.lua, lua/codecompanion/strategies/chat/init.lua, tests/strategies/chat/test_chat.lua
This PR adds the option to automatically load tools when opening a new chat.
=> Add `default_tools` option to chat strategy

lua/codecompanion/providers/completion/blink/init.lua
The `blink` provider stored the completions once when loaded, which meant that completions added later by extensions such as mcphub.nvim weren't included.
Fix this by always fetching the latest completions, like we already do in the `cmp` and `coc` providers:
- https://github.com/olimorris/codecompanion.nvim/blob/ba7bee5ce1883dd7585fc1f423f2bc82fbdf51a6/lua/codecompanion/providers/completion/cmp/variables.lua#L24
- https://github.com/olimorris/codecompanion.nvim/blob/ba7bee5ce1883dd7585fc1f423f2bc82fbdf51a6/lua/codecompanion/providers/completion/cmp/slash_commands.lua#L24
- https://github.com/olimorris/codecompanion.nvim/blob/ba7bee5ce1883dd7585fc1f423f2bc82fbdf51a6/lua/codecompanion/providers/completion/coc/init.lua#L82-L86
I saw this was discussed in …
=> fix(completion): always use latest completions in blink provider

doc/codecompanion.txt, doc/installation.md
I wanted to share this configuration snippet to make the chat buffer look a bit nicer :grinning: If you think it's overkill to have it in the docs I'd also be happy to post it as a discussion instead.
This is based on the examples at https://github.com/OXY2DEV/markview.nvim/wiki/HTML#container_elements
=> docs: link to examples to conceal tags with Markview

doc/codecompanion.txt, doc/configuration/chat-buffer.md, doc/getting-started.md, doc/usage/events.md, lua/codecompanion/commands.lua, lua/codecompanion/init.lua, lua/codecompanion/providers/completion/init.lua, lua/codecompanion/strategies/chat/agents/init.lua, lua/codecompanion/strategies/chat/agents/tool_filter.lua, tests/config.lua, tests/strategies/chat/agents/test_tool_filter.lua, tests/strategies/chat/test_references.lua
Future tools will have dependencies and this PR enables them to be conditionally loaded.
For performance reasons, we cache their availability and add a command to refresh the cache, perhaps after a dependency has been installed.
=> feat(tools): can be conditionally loaded

lua/codecompanion/strategies/chat/agents/init.lua
This fixes an error I made in this PR: https://github.com/olimorris/codecompanion.nvim/pull/1552
I mis-typed [this](https://github.com/olimorris/codecompanion.nvim/pull/1552/files#diff-9cbd4b342833a2597fc285c8b38bb5f46c086dd4a675aeddb7a7da387f6623baR361) line, which doesn't do anything.
I'm sorry for the mistake!
=> Fix: require tool module path correctly

doc/codecompanion.txt, doc/extending/workspace.md, lua/codecompanion/strategies/chat/slash_commands/buffer.lua, lua/codecompanion/strategies/chat/slash_commands/init.lua, lua/codecompanion/strategies/chat/slash_commands/workspace.lua, tests/strategies/chat/slash_commands/test_workspace.lua
When opening a workspace file, CodeCompanion will now detect if a file in a group is open as a buffer in Neovim. If so, then it will add that the file as a buffer in the chat buffer, automatically watching it in the process (if the user hasn't changed the defaults)
=> files can be opened as buffers in a workspace

doc/codecompanion.txt, doc/usage/chat-buffer/index.md, lua/codecompanion/adapters/copilot.lua, lua/codecompanion/config.lua, lua/codecompanion/strategies/chat/keymaps.lua, lua/codecompanion/utils/ui.lua, tests/adapters/test_copilot.lua
This PR adds a feature to display GitHub Copilot [usage statistics](https://docs.github.com/en/copilot/managing-copilot/understanding-and-managing-copilot-usage/monitoring-your-copilot-usage-and-entitlements), similar to what's available in VSCode, JetBrains IDEs, and other editors. Users can now check their quota usage directly within CodeCompanion without switching to other tools or waiting an email from GitHub (when requesting usage data).
**Note**: Premium interactions quota applies to all models except `gpt-4.1` and `gpt-4o`.
Press `gS` in any Copilot chat buffer to display a centered floating window showing:
- Premium interactions usage with percentage and color coding
- Chat quota status (those added for users uses free copilot)
- Completions quota status (those added for users …
=> Add Copilot Usage Statistics Feature with `gS` as default keymap

lua/codecompanion/strategies/chat/slash_commands/buffer.lua, lua/codecompanion/strategies/chat/slash_commands/init.lua, tests/strategies/chat/slash_commands/test_workspace.lua
If a file is added as a buffer, the description from the workspace file is now incorporated with it.
=> add description to buffer content in workspace

lua/codecompanion/strategies/chat/init.lua
Harden `Chat.last_chat` to validate whether the buffer was deleted or not, and if it was, clean it up with `:close()` and return `nil`. The net result of this required wrapping the deleted buffer call in `close` with a pcall just in case.
Hopefully I'm not coming across as annoying, but I do think it's good to gracefully handle buffer deletion cases since they can come in many forms (from other plugins or various work flows) 😬
Fixes #1744
The original issue has an example broken case when using the Toggle API. However there was an additional case if you use CodeCompanion History extension and you did `:bd` on an existing chat buffer, you could never access that particular history item again until you restarted neovim. Here's a video showing those flows being fixed with these changes: …
=> Ensure chat buffers gracefully handle buffer deletion

doc/usage/chat-buffer/agents.md, lua/codecompanion/adapters/tavily.lua, lua/codecompanion/strategies/chat/agents/tools/web_search.lua, tests/adapters/test_tavily.lua
This allows the LLM to search from a (or some) specific websites, similar to the `site:` trick for Google search. This makes it easier if you know _just_ where to look for the correct info, but the LLM don't.
Ref: https://docs.tavily.com/documentation/api-reference/endpoint/search#body-include-domains
=> enable domain specific web search for tavily adapter and `@web_search` tool

doc/codecompanion.txt, doc/installation.md
The link to ripgrep was not showing as a link because was inside a inline block code.
=> docs: fix markdown for ripgrep link

lua/codecompanion/adapters/copilot/helpers.lua, lua/codecompanion/adapters/copilot/init.lua, tests/adapters/copilot/test_helpers.lua
Fix `Unauthorized: token expired` error after prompting inactivity.
The issue seems to be caused by [models cache](https://github.com/olimorris/codecompanion.nvim/blob/3527a9c85b58a8db2fee6d7dcde72077ba790a4a/lua/codecompanion/config.lua#L33) refresh after some time. The copilot adapter function [is given a _github_token](https://github.com/olimorris/codecompanion.nvim/blob/3527a9c85b58a8db2fee6d7dcde72077ba790a4a/lua/codecompanion/adapters/copilot/init.lua#L303C48-L303C71) but that token can be outdated and refreshed by `get_and_authorize_token` call inside the function. Despite this the function would still use the outdated token from input when calling the models endpoint.
- Fixes #1052
=> Fix: copilot adapter unauthorized token expired

lua/codecompanion/strategies/chat/ui/init.lua
As mentioned in #1791, the `CodeCompanionChatOpened` and `CodeCompanionChatHidden` events currently do not provide the chat ID in the event data. This PR adds that.
Implements #1791 
Note the `id` is set.
=> fix: add chat ID to chat opened/hidden events

lua/codecompanion/strategies/inline/init.lua
I suppose there is a conflict between telescope and dressing triggered by switching from Action Palette (telescope) to "Custom Prompt" (dressing). The "Custom Prompt" so far is the only inline prompt with `user_prompt = true`, so it triggers `vim.ui.input()` right after leaving telescope selection menu. Telescope selection menu was in INSERT mode, and I think it tries to leave it on exiting from menu. Dressing in turn tries to enable INSERT mode on showing `vim.ui.input` - and fails (it calls `vim.cmd("startinsert!")` without any effect).
If I disable any one of telescope or dressing this issue disappears.
Adding `vim.schedule` fixes the issue. But I didn't checked the whole codebase - there are may be other similar issues somewhere too.
I've no idea is it possible to write a test for the …
=> fix(inline): user_prompt mode with dressing and telescope

lua/codecompanion/init.lua, lua/codecompanion/strategies/chat/agents/tools/insert_edit_into_file.lua
This ensures that the chat buffer is visible after a user accepts an edit with the `insert_edit_into_file` tool.
#1788
=> add restore function to ensure a chat buffer can be made visible

lua/codecompanion/strategies/chat/agents/tools/read_file.lua, tests/strategies/chat/agents/tools/test_read_file.lua
The "read_file" tools currently throws, when the LLM what's to read a file until a line, which is greater than the actual file length. This PR removes the error and replaces the to high end_line with the actual last line.
#1819
=> fix(read_file): read entire file, when end_line is greater than file

lua/codecompanion/strategies/chat/agents/tools/read_file.lua
Improves the error messages that are sent from the `read_file` tool
=> improve read_file tool error messages

lua/codecompanion/strategies/chat/ui/formatters/tools.lua
If an LLM went from reasoning->tool output, the `response` header would not be output in the chat buffer.
=> better handle reasoning output if a tool response follows

lua/codecompanion/strategies/chat/ui/tools.lua
Wraps the tool folding in a pcall.
=> wrap tool folding in pcall

doc/codecompanion.txt, doc/usage/chat-buffer/agents.md, lua/codecompanion/config.lua, lua/codecompanion/strategies/chat/agents/tools/helpers/patch.lua, lua/codecompanion/strategies/chat/agents/tools/insert_edit_into_file.lua, tests/config.lua, tests/strategies/chat/agents/tools/helpers/test_patch.lua
This PR allows users to specify their own patching algorithm for the `insert_edit_into_file` tool. Also swaps out the word `changes` for `edits` in the default algorithm.
#1619
=> patching algorithm can be swapped out

lua/codecompanion/strategies/chat/slash_commands/init.lua
Custom prompts which had a URL would fail
#1843
=> fix custom prompts containing URLs

lua/codecompanion/strategies/chat/agents/tools/helpers/wait.lua, lua/codecompanion/strategies/chat/watchers.lua, tests/strategies/chat/agents/tools/helpers/test_wait.lua
Minor PR ensuring that autocmd's are uniformly named.
=> refactor autocmd names

lua/codecompanion/strategies/chat/agents/tools/read_file.lua
Clean up the error messages on the read_file tool
=> refactor(tools): read_file error message

lua/codecompanion/adapters/huggingface.lua
This PR updates the Hugging Face adapter to fix HuggingFace API endpoint and model selection.
**Key changes:**
- Updates the API endpoint for chat completions to `https://router.huggingface.co/v1/chat/completions`.
- Adds a `get_models` function to dynamically fetch available models from the new Hugging Face API endpoint (`/api/models?inference_provider=all`), with caching and fallback support.
some source for anyone to read more about how new API works:
[Inference Provider](https://huggingface.co/docs/inference-providers/index?python-clients=requests&javascript-clients=huggingface.js)
[Hub API](https://huggingface.co/docs/inference-providers/hub-api?code=curl)
Fix #1864 
It’s worth mentioning that we currently have several different versions of the `get_models` function across multiple …
=> fix(huggingface): update to use new HuggingFace API endpoint

lua/codecompanion/commands.lua
The regex in the complete function did not match on the "/" needed to reference elements from the prompt library. Prompt library elements would appear only if "/" was not used.
Fixes #1885
=> fix(commands): CodeCompanion complete from prompt library.

lua/codecompanion/adapters/ollama.lua
With the change to using Ollama's native API in #1829, returning of the default model broke, as models are now stored in a table by name. This meant that the model selection list was empty, as `change_adapter` in `strategies/chat/keymaps.lua` ended up creating a table of models that `vim.ui.select` could not render.
This PR uses the underlying API response to return the first-returned (newest) available model _name_ as the default.
It wasn't obvious where test coverage could be added for this, as it looked like adapter schema is mocked in `test_ollama.lua`.
=> fix(ollama): ensure default model returns

lua/codecompanion/strategies/chat/agents/executor/func.lua
Prevents the issue when trying to log a nonexistent tool in `func.lua`
=> fix error outputting tool name when completed

lua/codecompanion/adapters/copilot/helpers.lua, lua/codecompanion/adapters/copilot/init.lua, tests/adapters/copilot/test_helpers.lua
There’s an issue where Copilot doesn’t retrieve models correctly because the `get_models` GitHub endpoint expects a GitHub token rather than an OAuth token. It’s still surprising that the API didn’t return any errors when we used the wrong token.
This PR addresses the issue, but I would appreciate it if you could test it before merging to ensure everything is working smoothly.
Thank you
#1874
=> fix(copilot): correctly retrieve token in get_models

CONTRIBUTING.md, lua/codecompanion/adapters/githubmodels.lua
This changes the url for the `githubmodels` adapter from a [deprecated one](https://github.blog/changelog/2025-07-17-deprecation-of-azure-endpoint-for-github-models/) to the supported [GitHub Models REST API](https://docs.github.com/en/rest/models).
NOTE: There are some existing bugs, that I did not fix in this PR. In testing different models I found that `o3-mini` fails on both the old endpoint and the new. There may be others, but I chose not to expand the scope of this PR as the default option **does** work.
For: https://github.com/olimorris/codecompanion.nvim/discussions/1909
<details>
<summary>o3-mini max tokens error message</summary>
</details>
<details>
<summary>Error message from manually testing a url with a typo</summary>
</details>
<details>
<summary>make all works</summary> …
=> Change the githubmodels url to use the GitHub Rest API

lua/codecompanion/http.lua
Events through the `http.lua` file were not getting fired accordingly
#1918
=> fix events

lua/codecompanion/strategies/chat/debug.lua
When I want to quit from Debug Chat, it is tedious to have to do `:q<return>` (three keypresses). It should be possible to just quit using `q` or `Esc`. That feature exists but `ignore_keymaps` is set to `true` when creating the floating window. Set `ignore_keymaps` to false.
=> fix(ui): Debug Chat: allow `q` and `<Esc>` to be able to close the window

doc/codecompanion.txt, doc/extending/prompts.md, lua/codecompanion/strategies/chat/helpers.lua, lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/strategies/chat/ui/init.lua, lua/codecompanion/strategies/init.lua
- This PR allows users to alter the intro message in the chat buffer for their custom prompts
- It also removes the requirement for users to supply an empty `user` message in their prompt library items
=> Prompt Library: Allow custom intro message and now don't require a user prompt

lua/codecompanion/strategies/chat/init.lua
Removes a redundant function in the chat buffer
=> refactor check for user messages

lua/codecompanion/strategies/chat/init.lua, tests/adapters/test_tools_in_chat_buffer.lua
Don't redefine the schema variable in the chat buffer
=> refactor(chat): do not redefine schema

lua/codecompanion/strategies/inline/variables/init.lua
Fixes the context issue which arose from a recent refactor
#1954
=> fix: variables for inline strategy

lua/codecompanion/strategies/inline/init.lua
When you switch the buffer after triggering the inline strategy, the [cursor movement](https://github.com/olimorris/codecompanion.nvim/blob/19d665a9b13c0b05652c359c4302465b8b2543be/lua/codecompanion/strategies/inline/init.lua#L172) results in various issues:
- If the current buffer has more rows than the row at the buffer where the request was made, the cursor moves in the current buffer. Somewhat negligible, but nonetheless irritating to move to a random, unrelated location.
- If the current buffer has fewer rows than the buffer where the request was made, the cursor cannot be moved following error is thrown:
```
Error executing vim.schedule lua callback: ...panion.nvim/lua/codecompanion/strategies/inline/init.lua:172: Cursor position outside buffer
[C]: in function …
```
=> fix(inline): replacement broken when user switched buffer in meantime

lua/codecompanion/strategies/chat/init.lua
Previously, for models like `gpt-4.1`, there would be no space between the header and the tool output. This was caused by the LLM responding with just the tool output and no message. This resulted in the `state.last_type` in the UI Builder being left as `tool_message` from one response to the next.
This PR changes that by adding the notion of `user_message` if the user submits a message.
=> fix(ui): tool spacing in chat buffer

doc/configuration/chat-buffer.md, doc/usage/chat-buffer/variables.md, doc/usage/events.md, lua/codecompanion/config.lua, lua/codecompanion/providers/completion/init.lua, lua/codecompanion/strategies/chat/debug.lua, lua/codecompanion/strategies/chat/variables/buffer.lua, lua/codecompanion/strategies/chat/variables/init.lua, lua/codecompanion/types.lua, lua/codecompanion/utils/buffers.lua, plugin/codecompanion.lua, tests/strategies/chat/test_variables.lua
This PR will improve how buffer variables work in the chat buffer, significantly:
This should work for all completion providers as I won't be touching a line of their code.
=> feat(chat): improve buffer variables/context

lua/codecompanion/strategies/chat/variables/buffer.lua
Fixes an issue in #1967 where `_G.codecompanion_current_context` hadn't been set and the buffer variable had nothing to fall back on.
=> fix(chat): buffer var with no context

doc/usage/ui.md, lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/strategies/chat/keymaps.lua
Add a global table that users can leverage throughout their config.
https://github.com/user-attachments/assets/a37180a0-0f1b-4ffb-8fae-44669e9d3df7
=> feat(chat): global metadata

plugin/codecompanion.lua
Put check in place to prevent the below issue from occurring when a buffer may not be valid
#1983
=> fix: ensure buffer is valid

lua/codecompanion/strategies/chat/tools/catalog/list_code_usages/init.lua, tests/strategies/chat/tools/catalog/list_code_usages/test_list_code_usages.lua
The list code usage tool was impacted by #1891. The tests underpinning this tool were too heavily mocked resulting in them not being able to catch the error.
#2018
=> fix(tools): list code usages tool

lua/codecompanion/config.lua, lua/codecompanion/strategies/chat/init.lua
In the off chance that this may improve performance in the chat buffer, setting it as a default.
#552
=> perf(chat): set undolevels to 10

lua/codecompanion/adapters/http/copilot/helpers.lua, lua/codecompanion/strategies/chat/debug.lua, lua/codecompanion/strategies/chat/helpers/super_diff.lua, lua/codecompanion/strategies/chat/keymaps.lua, lua/codecompanion/utils/ui.lua
This is a small fix to display the correct `sign_text` in floating diffs. The `open_window` function with option `style = "minimal"` prevents signs from showing up properly, so it’s better to leave the `style = "minimal"` option to the module rather than enforcing it inside the general `create_float` function.
Sign texts don’t appear near deleted lines (virtual text) in inline diffs.
Thank you
Current behavior: no `sign_text` indicator appears next to the virtual lines highlighted in red.
=> fix(diff): display the correct `sign_text` in floating diffs

codecompanion-workspace.json
Refactor CodeCompanion's workspace file to not use system prompts.
=> refactor(workspace): update CodeCompanion's

lua/codecompanion/adapters/http/copilot/get_models.lua, lua/codecompanion/adapters/http/copilot/init.lua, lua/codecompanion/adapters/http/copilot/token.lua, lua/codecompanion/adapters/http/init.lua
When a user first initiates a chat buffer with the Copilot adapter, and tries to do an operation like change the model or open the debug window, there's an initial delay as both of those activities call the models endpoint in a blocking manner.
This PR ensures that when the Copilot adapter is resolved anywhere within the plugin, the models are fetched async and cached.
The chat buffer and Copilot should feel snappier.
Also removed redundant event.
=> refactor(adapters): fetch copilot models async at resolve

lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/types.lua
Better type warnings with the LSP.
=> chore: add message types

lua/codecompanion/strategies/init.lua
Previously the `pre_hook` function in the prompt library is only called for inline strategy. This PR enables this hook for chat strategy too, so that users [can run code to prepare custom workflow](https://github.com/Davidyz/VectorCode/pull/264).
With this PR and [the vectorcode WIP feature that requires this](https://github.com/Davidyz/VectorCode/pull/264), we would be able also to have [this](https://github.com/olimorris/codecompanion.nvim/pull/1741#issuecomment-3015999094), but without the web search tool.
https://github.com/Davidyz/VectorCode/pull/264
=> Support `pre_hook` option in prompt library when applicable for chat strategy.

doc/extending/workflows.md, lua/codecompanion/strategies/init.lua
Can set adapters (models included) in a specific workflow.
=> Can set adapter to workflows

lua/codecompanion/strategies/inline/init.lua
When vim.json.decode() fails, it returns an error message. So the second return value from pcall() will be truthy even when an error occurs.
=> fix(inline): Check result from vim.json.decode pcall

doc/codecompanion.txt, doc/configuration/adapters.md, lua/codecompanion/config.lua, lua/codecompanion/init.lua
This PR allows the hiding of default ACP adapters. This was already possible for the default HTTP adapters.
See discussion: https://github.com/olimorris/codecompanion.nvim/discussions/2083
=> feat(adapters): allow hiding of acp adapters

lua/codecompanion/strategies/inline/init.lua
The change from adapters to adapters.http and adapters.acp broke the inline parsing for adapters when you do
```
:CodeCompanion <adapter> prompt
```
I used the same "hack" that is used inside adapters/init.lua to generate the full table of possible adapters. I also added a comment to change it as soon as v18 ships. 
I do not really have time right now to look at adding a test for this... I only checked manually with both default and custom adapters and it works.
=> Fix inline adapter parsing after ACP integration

lua/codecompanion/strategies/chat/init.lua
This allows subscribers to the CodeCompanionChatClosed, Adapter, and Model functions to use the Neovim buffers. Otherwise, an invalid bufnr is passed to the event handler.
For my use case, I would like to be able to save a chat before it is cleared or closed. For cleared, we would either need to move when that event is fired or create a new event right before it is cleared.
=> Move chat close events to fire before clearing the buffers.

lua/codecompanion/init.lua
=> refactor: clean up init.lua

lua/codecompanion/strategies/chat/memory/helpers.lua
Alert the user that a memory file couldn't be added to the chat buffer.
=> refactor(chat): add warning when memory file can't be found

lua/codecompanion/strategies/chat/acp/formatters.lua, lua/codecompanion/strategies/chat/acp/handler.lua
Claude Code likes to output its tool requests into the chat buffer. For now. hide this to make sure we don't break the buffer.
=> fix(chat): clip claude code tool output

lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/strategies/chat/keymaps.lua, lua/codecompanion/strategies/chat/slash_commands/workspace.lua, lua/codecompanion/strategies/chat/tool_registry.lua
Make it easier to change the adapter and model from elsewhere in the plugin.
=> refactor(chat): add change_adapter helper

.codecompanion/workflows.md, doc/codecompanion.txt, doc/extending/workflows.md, lua/codecompanion/strategies/init.lua
Add the ability to change adapters and models on each prompt.
=> feat(workflows): can change adapter on each prompt

.codecompanion/tests/test.md, .codecompanion/tools.md, lua/codecompanion/config.lua
Add memory for tests and tools
=> chore: add memory for testing and tools

lua/codecompanion/utils/ui.lua
Support custom values `winhighlight` in `config.display.chat.diff_window.opts.winhighlight`.
- Fixes #2165
=> fix(ui): try to append to existing winhighlight option values

lua/codecompanion/adapters/acp/claude_code.lua, lua/codecompanion/adapters/acp/init.lua, lua/codecompanion/strategies/chat/acp/formatters.lua
Ensure Claude Code does output markdown when returning an erroneous tool
=> fix(acp): fix claude-code always outputting tool content

lua/codecompanion/strategies/chat/slash_commands/helpers.lua, lua/codecompanion/strategies/chat/slash_commands/symbols.lua
This makes the `/symbols` slash command work with files that don't have an extension, e.g. a Python script without `.py`.
Since we already load the file contents to get the symbols we can just pass it to `vim.filetype.match` to improve the detection.
Use `unpack()` in the tests to get multiple return values through `lua_get()`, which only seems to support returning a single value.
=> fix(symbols): also use file contents to detect filetype

lua/codecompanion/providers/diff/inline.lua, lua/codecompanion/providers/diff/utils.lua, lua/codecompanion/strategies/chat/edit_tracker.lua, lua/codecompanion/strategies/chat/helpers/super_diff.lua, lua/codecompanion/strategies/inline/keymaps.lua, tests/providers/diff/test_inline.lua, tests/providers/diff/test_utils.lua
I was taking a look at our diff implementation the other day and thought I'd take the time to rename some of the variables so they're a little bit more explicit.
=> refactor(ui): rename vars in diff implementation

lua/codecompanion/adapters/http/copilot/get_models.lua
In Copilot, gpt-5-codex, requires the responses endpoint which is currently unsupported. This PR prevents the model from showing up in the model list.
=> refactor(adapters): don't display gpt-5-codex

lua/codecompanion/strategies/chat/tools/orchestrator.lua, tests/strategies/chat/tools/test_orchestrator.lua
Parameter quoting rules on Windows are complicated, because Windows programs only receive one big string with all arguments which they or msvcrt split back into argv. libuv used by NeoVim tries to be helpful, but ends up sending literal quotes to cmd.exe (programs get `"C:\file.txt"` with quotes instead of `C:\file.txt`) or not literal enough to powershell (literal empty arguments `""` get lost along the way)
For those who don't doze on their wind: https://web.archive.org/web/20190109172835/https://blogs.msdn.microsoft.com/twistylittlepassagesallalike/2011/04/23/everyone-quotes-command-line-arguments-the-wrong-way/
Creating a temporary .bat file and executing it _almost_ works, but I have had the LLM propose running `for ... %i ...` commands which require doubling up the percentage sign. …
=> fix(chat): Fix the run_command tool on Windows (#2179)

lua/codecompanion/acp/init.lua, lua/codecompanion/acp/prompt_builder.lua, lua/codecompanion/http.lua, lua/codecompanion/strategies/chat/init.lua, lua/codecompanion/strategies/inline/init.lua, tests/acp/test_prompt_builder.lua
Ensure's that ACP clients can be cancelled in the chat buffer.
#2223
=> fix(acp): ensure jobs can be cancelled
